namespace Eagle.Core.Settings
{
    public class ModuleCapabilitySetting
    {
        public const string VIEW_APPLICATION = "VIEW_APPLICATION";
        public const string ADD_APPLICATION = "ADD_APPLICATION";
        public const string EDIT_APPLICATION = "EDIT_APPLICATION";
        public const string DELETE_APPLICATION = "DELETE_APPLICATION";
        public const string VIEW_HOST_LANGUAGES = "VIEW_HOST_LANGUAGES";
        public const string ADD_HOST_LANGUAGES = "ADD_HOST_LANGUAGES";
        public const string EDIT_HOST_LANGUAGES = "EDIT_HOST_LANGUAGES";
        public const string UPDATE_STATUS_HOST_LANGUAGES = "UPDATE_STATUS_HOST_LANGUAGES";
        public const string VIEW_EVENTS = "VIEW_EVENTS";
        public const string ADD_EVENTS = "ADD_EVENTS";
        public const string EDIT_EVENTS = "EDIT_EVENTS";
        public const string DELETE_EVENTS = "DELETE_EVENTS";
        public const string PUBLISH_EVENTS = "PUBLISH_EVENTS";
        public const string VIEW_HOST___MODULES = "VIEW_HOST___MODULES";
        public const string ADD_HOST___MODULES = "ADD_HOST___MODULES";
        public const string EDIT_HOST___MODULES = "EDIT_HOST___MODULES";
        public const string DELETE_HOST___MODULES = "DELETE_HOST___MODULES";
        public const string VIEW_SECURITY_ROLES = "VIEW_SECURITY_ROLES";
        public const string ADD_SECURITY_ROLES = "ADD_SECURITY_ROLES";
        public const string EDIT_SECURITY_ROLES = "EDIT_SECURITY_ROLES";
        public const string DELETE_SECURITY_ROLES = "DELETE_SECURITY_ROLES";
        public const string VIEW_TAXONOMY = "VIEW_TAXONOMY";
        public const string ADD_TAXONOMY = "ADD_TAXONOMY";
        public const string EDIT_TAXONOMY = "EDIT_TAXONOMY";
        public const string DELETE_TAXONOMY = "DELETE_TAXONOMY";
        public const string VIEW_FILE_MANAGER = "VIEW_FILE_MANAGER";
        public const string ADD_FILE_MANAGER = "ADD_FILE_MANAGER";
        public const string EDIT_FILE_MANAGER = "EDIT_FILE_MANAGER";
        public const string DELETE_FILE_MANAGER = "DELETE_FILE_MANAGER";
        public const string VIEW_PERMISSIONS = "VIEW_PERMISSIONS";
        public const string VIEW = "View";
        public const string VIEW_MEDIA_VIDEO = "VIEW_MEDIA_VIDEO";
        public const string CREATE_MEDIA_VIDEO = "CREATE_MEDIA_VIDEO";
        public const string EDIT_MEDIA_VIDEO = "EDIT_MEDIA_VIDEO";
        public const string DELETE_MEDIA_VIDEO = "DELETE_MEDIA_VIDEO";
        public const string MEDIA_AUDIO_MEDIA_AUDIO = "MEDIA_AUDIO_MEDIA_AUDIO";
        public const string VIEW_MEDIA_ALBUM = "VIEW_MEDIA_ALBUM";
        public const string ADD_MEDIA_ALBUM = "ADD_MEDIA_ALBUM";
        public const string EDIT_MEDIA_ALBUM = "EDIT_MEDIA_ALBUM";
        public const string DELETE_MEDIA_ALBUM = "DELETE_MEDIA_ALBUM";
        public const string VIEW_MEDIA_TOPIC = "VIEW_MEDIA_TOPIC";
        public const string ADD_MEDIA_TOPIC = "ADD_MEDIA_TOPIC";
        public const string EDIT_MEDIA_TOPIC = "EDIT_MEDIA_TOPIC";
        public const string DELETE_MEDIA_TOPIC = "DELETE_MEDIA_TOPIC";
        public const string VIEW_MEDIA_ARTIST = "VIEW_MEDIA_ARTIST";
        public const string ADD_MEDIA_ARTIST = "ADD_MEDIA_ARTIST";
        public const string EDIT_MEDIA_ARTIST = "EDIT_MEDIA_ARTIST";
        public const string DELETE_MEDIA_ARTIST = "DELETE_MEDIA_ARTIST";
        public const string VIEW_MEDIA_COMPOSER = "VIEW_MEDIA_COMPOSER";
        public const string ADD_MEDIA_COMPOSER = "ADD_MEDIA_COMPOSER";
        public const string EDIT_MEDIA_COMPOSER = "EDIT_MEDIA_COMPOSER";
        public const string DELETE_MEDIA_COMPOSER = "DELETE_MEDIA_COMPOSER";
        public const string VIEW_COMPANY = "VIEW_COMPANY";
        public const string CREATE_COMPANY = "CREATE_COMPANY";
        public const string EDIT_COMPANY = "EDIT_COMPANY";
        public const string DELETE_COMPANY = "DELETE_COMPANY";
        public const string VIEW_PRODUCT_DISCOUNT = "VIEW_PRODUCT_DISCOUNT";
        public const string CREATE_PRODUCT_DISCOUNT = "CREATE_PRODUCT_DISCOUNT";
        public const string EDIT_PRODUCT_DISCOUNT = "EDIT_PRODUCT_DISCOUNT";
        public const string DELETE_PRODUCT_DISCOUNT = "DELETE_PRODUCT_DISCOUNT";
        public const string VIEW_CURRENCY = "VIEW_CURRENCY";
        public const string CREATE = "Create";
        public const string EDIT = "Edit";
        public const string DELETE = "Delete";
        public const string VIEW_DOCUMENT_FOLDER = "VIEW_DOCUMENT_FOLDER";
        public const string VIEW_DOCUMENT_FILE = "VIEW_DOCUMENT_FILE";
        public const string ADD_MEDIA_PLAYLIST = "ADD_MEDIA_PLAYLIST";
        public const string EDIT_MEDIA_PLAYLIST = "EDIT_MEDIA_PLAYLIST";
        public const string DELETE_MEDIA_PLAYLIST = "DELETE_MEDIA_PLAYLIST";
        public const string VIEW_MEDIA_PLAYLIST = "VIEW_MEDIA_PLAYLIST";
        public const string VIEW_SHIPPING_METHOD = "VIEW_SHIPPING_METHOD";
        public const string ADD_SHIPPING_METHOD = "ADD_SHIPPING_METHOD";
        public const string EDIT_SHIPPING_METHOD = "EDIT_SHIPPING_METHOD";
        public const string DELETE_SHIPPING_METHOD = "DELETE_SHIPPING_METHOD";
        public const string VIEW_BOOKING_SERVICE = "VIEW_BOOKING_SERVICE";
        public const string ADD_EMPLOYEE = "ADD_EMPLOYEE";
        public const string EDIT_EMPLOYEE = "EDIT_EMPLOYEE";
        public const string VIEW_EMPLOYEE = "VIEW_EMPLOYEE";
        public const string ADD_NOTIFICATION_TYPE = "ADD_NOTIFICATION_TYPE";
        public const string EDIT_NOTIFICATION_TYPE = "EDIT_NOTIFICATION_TYPE";
        public const string VIEW_NOTIFICATION_TYPE = "VIEW_NOTIFICATION_TYPE";
        public const string VIEW_SERVICE_BOOKING = "VIEW_SERVICE_BOOKING";
        public const string CREATE_SERVICE_BOOKING = "CREATE_SERVICE_BOOKING";
        public const string EDIT_SERVICE_BOOKING = "EDIT_SERVICE_BOOKING";
        public const string DELETE_SERVICE_BOOKING = "DELETE_SERVICE_BOOKING";
        public const string VIEW_SERVICE_DISCOUNT = "VIEW_SERVICE_DISCOUNT";
        public const string CREATE_SERVICE_DISCOUNT = "CREATE_SERVICE_DISCOUNT";
        public const string EDIT_SERVICE_DISCOUNT = "EDIT_SERVICE_DISCOUNT";
        public const string DELETE_SERVICE_DISCOUNT = "DELETE_SERVICE_DISCOUNT";
        public const string VIEW_SERVICE_PACK = "VIEW_SERVICE_PACK";
        public const string CREATE_SERVICE_PACK = "CREATE_SERVICE_PACK";
        public const string EDIT_SERVICE_PACK = "EDIT_SERVICE_PACK";
        public const string DELETE_SERVICE_PACK = "DELETE_SERVICE_PACK";
        public const string VIEW_JOB_POSITION = "VIEW_JOB_POSITION";
        public const string CREATE_JOB_POSITION = "CREATE_JOB_POSITION";
        public const string EDIT_JOB_POSITION = "EDIT_JOB_POSITION";
        public const string DELETE_JOB_POSITION = "DELETE_JOB_POSITION";
        public const string VIEW_CONTRACT = "VIEW_CONTRACT";
        public const string ADD_CONTRACT = "ADD_CONTRACT";
        public const string EDIT_CONTRACT = "EDIT_CONTRACT";
        public const string DELETE_CONTRACT = "DELETE_CONTRACT";
        public const string ADD_SERVICE_PACK_DURATION = "ADD_SERVICE_PACK_DURATION";
        public const string EDIT_SERVICE_PACK_DURATION = "EDIT_SERVICE_PACK_DURATION";
        public const string DELETE_SERVICE_PACK_DURATION = "DELETE_SERVICE_PACK_DURATION";
        public const string VIEW_SERVICE_PACK_DURATION = "VIEW_SERVICE_PACK_DURATION";
        public const string VIEW_BOOKING_CALENDAR = "VIEW_BOOKING_CALENDAR";
        public const string CREATE_BOOKING_CALENDAR = "CREATE_BOOKING_CALENDAR";
        public const string EDIT_BOOKING_CALENDAR = "EDIT_BOOKING_CALENDAR";
        public const string DELETE_BOOKING_CALENDAR = "DELETE_BOOKING_CALENDAR";
        public const string VIEW_MESSAGE_TYPE = "VIEW_MESSAGE_TYPE";
        public const string CREATE_MESSAGE_TYPE = "CREATE_MESSAGE_TYPE";
        public const string EDIT_MESSAGE_TYPE = "EDIT_MESSAGE_TYPE";
        public const string UPDATE_STATUS_MESSAGE_TYPE = "UPDATE_STATUS_MESSAGE_TYPE";
        public const string VIEW_SKIN_PACKAGE_TYPE = "VIEW_SKIN_PACKAGE_TYPE";
        public const string CREATE_SKIN_PACKAGE_TYPE = "CREATE_SKIN_PACKAGE_TYPE";
        public const string EDIT_SKIN_PACKAGE_TYPE = "EDIT_SKIN_PACKAGE_TYPE";
        public const string DELETE_SKIN_PACKAGE_TYPE = "DELETE_SKIN_PACKAGE_TYPE";
        public const string VIEW_SKIN_PACKAGE_TEMPLATE = "VIEW_SKIN_PACKAGE_TEMPLATE";
        public const string CREATE_SKIN_PACKAGE_TEMPLATE = "CREATE_SKIN_PACKAGE_TEMPLATE";
        public const string EDIT_SKIN_PACKAGE_TEMPLATE = "EDIT_SKIN_PACKAGE_TEMPLATE";
        public const string DELETE_SKIN_PACKAGE_TEMPLATE = "DELETE_SKIN_PACKAGE_TEMPLATE";
        public const string VIEW_SKIN_PACKAGE_BACKGROUND = "VIEW_SKIN_PACKAGE_BACKGROUND";
        public const string CREATE_SKIN_PACKAGE_BACKGROUND = "CREATE_SKIN_PACKAGE_BACKGROUND";
        public const string EDIT_SKIN_PACKAGE_BACKGROUND = "EDIT_SKIN_PACKAGE_BACKGROUND";
        public const string DELETE_SKIN_PACKAGE_BACKGROUND = "DELETE_SKIN_PACKAGE_BACKGROUND";
        public const string VIEW_EVENT_TYPE = "VIEW_EVENT_TYPE";
        public const string CREATE_EVENT_TYPE = "CREATE_EVENT_TYPE";
        public const string EDIT_EVENT_TYPE = "EDIT_EVENT_TYPE";
        public const string DELETE_EVENT_TYPE = "DELETE_EVENT_TYPE";
        public const string VIEW_NOTIFICATION_TARGET = "VIEW_NOTIFICATION_TARGET";
        public const string EDIT_NOTIFICATION_TARGET = "EDIT_NOTIFICATION_TARGET";
        public const string VIEW_SERVICE_CATEGORY = "VIEW_SERVICE_CATEGORY";
        public const string CREATE_SERVICE_CATEGORY = "CREATE_SERVICE_CATEGORY";
        public const string EDIT_SERVICE_CATEGORY = "EDIT_SERVICE_CATEGORY";
        public const string DELETE_SERVICE_CATEGORY = "DELETE_SERVICE_CATEGORY";
        public const string CREATE_BOOKING_SERVICE = "CREATE_BOOKING_SERVICE";

        //// When adding new module capability also add to the module capabiltiy enum (below)
        public enum ModuleCapabilityType
        {
            VIEW_APPLICATION = 1,
            ADD_APPLICATION = 2,
            EDIT_APPLICATION = 3,
            DELETE_APPLICATION = 4,
            VIEW_HOST_LANGUAGES = 5,
            ADD_HOST_LANGUAGES = 6,
            EDIT_HOST_LANGUAGES = 7,
            UPDATE_STATUS_HOST_LANGUAGES = 8,
            VIEW_EVENTS = 9,
            ADD_EVENTS = 10,
            EDIT_EVENTS = 11,
            DELETE_EVENTS = 12,
            PUBLISH_EVENTS = 13,
            VIEW_HOST_MODULES = 14,
            ADD_HOST_MODULES = 15,
            EDIT_HOST_MODULES = 16,
            DELETE_HOST_MODULES = 17,
            VIEW_SECURITY_ROLES = 18,
            ADD_SECURITY_ROLES = 19,
            EDIT_SECURITY_ROLES = 20,
            DELETE_SECURITY_ROLES = 21,
            VIEW_TAXONOMY = 22,
            ADD_TAXONOMY = 23,
            EDIT_TAXONOMY = 24,
            DELETE_TAXONOMY = 25,
            VIEW_FILE_MANAGER = 26,
            ADD_FILE_MANAGER = 27,
            EDIT_FILE_MANAGER = 28,
            DELETE_FILE_MANAGER = 29,
            VIEW_PERMISSIONS = 30,
            View = 31,
            VIEW_MEDIA_VIDEO = 32,
            CREATE_MEDIA_VIDEO = 33,
            EDIT_MEDIA_VIDEO = 34,
            DELETE_MEDIA_VIDEO = 35,
            MEDIA_AUDIO_MEDIA_AUDIO = 36,
            VIEW_MEDIA_ALBUM = 37,
            ADD_MEDIA_ALBUM = 38,
            EDIT_MEDIA_ALBUM = 39,
            DELETE_MEDIA_ALBUM = 40,
            VIEW_MEDIA_TOPIC = 41,
            ADD_MEDIA_TOPIC = 42,
            EDIT_MEDIA_TOPIC = 43,
            DELETE_MEDIA_TOPIC = 44,
            VIEW_MEDIA_ARTIST = 45,
            ADD_MEDIA_ARTIST = 46,
            EDIT_MEDIA_ARTIST = 47,
            DELETE_MEDIA_ARTIST = 48,
            VIEW_MEDIA_COMPOSER = 49,
            ADD_MEDIA_COMPOSER = 50,
            EDIT_MEDIA_COMPOSER = 51,
            DELETE_MEDIA_COMPOSER = 52,
            VIEW_COMPANY = 53,
            CREATE_COMPANY = 54,
            EDIT_COMPANY = 55,
            DELETE_COMPANY = 56,
            VIEW_PRODUCT_DISCOUNT = 57,
            CREATE_PRODUCT_DISCOUNT = 58,
            EDIT_PRODUCT_DISCOUNT = 59,
            DELETE_PRODUCT_DISCOUNT = 60,
            VIEW_CURRENCY = 61,
            Create = 62,
            Edit = 63,
            Delete = 64,
            VIEW_DOCUMENT_FOLDER = 65,
            VIEW_DOCUMENT_FILE = 66,
            ADD_MEDIA_PLAYLIST = 67,
            EDIT_MEDIA_PLAYLIST = 68,
            DELETE_MEDIA_PLAYLIST = 69,
            VIEW_MEDIA_PLAYLIST = 70,
            VIEW_SHIPPING_METHOD = 71,
            ADD_SHIPPING_METHOD = 72,
            EDIT_SHIPPING_METHOD = 73,
            DELETE_SHIPPING_METHOD = 74,
            VIEW_BOOKING_SERVICE = 75,
            ADD_EMPLOYEE = 76,
            EDIT_EMPLOYEE = 77,
            VIEW_EMPLOYEE = 78,
            ADD_NOTIFICATION_TYPE = 79,
            EDIT_NOTIFICATION_TYPE = 80,
            VIEW_NOTIFICATION_TYPE = 81,
            VIEW_SERVICE_BOOKING = 1067,
            CREATE_SERVICE_BOOKING = 1068,
            EDIT_SERVICE_BOOKING = 1069,
            DELETE_SERVICE_BOOKING = 1070,
            VIEW_SERVICE_DISCOUNT = 1071,
            CREATE_SERVICE_DISCOUNT = 1072,
            EDIT_SERVICE_DISCOUNT = 1073,
            DELETE_SERVICE_DISCOUNT = 1074,
            VIEW_SERVICE_PACK = 1075,
            CREATE_SERVICE_PACK = 1076,
            EDIT_SERVICE_PACK = 1077,
            DELETE_SERVICE_PACK = 1078,
            VIEW_JOB_POSITION = 1079,
            CREATE_JOB_POSITION = 1080,
            EDIT_JOB_POSITION = 1081,
            DELETE_JOB_POSITION = 1082,
            VIEW_CONTRACT = 1083,
            ADD_CONTRACT = 1084,
            EDIT_CONTRACT = 1085,
            DELETE_CONTRACT = 1086,
            ADD_SERVICE_PACK_DURATION = 1087,
            EDIT_SERVICE_PACK_DURATION = 1088,
            DELETE_SERVICE_PACK_DURATION = 1089,
            VIEW_SERVICE_PACK_DURATION = 1090,
            VIEW_BOOKING_CALENDAR = 1091,
            CREATE_BOOKING_CALENDAR = 1092,
            EDIT_BOOKING_CALENDAR = 1093,
            DELETE_BOOKING_CALENDAR = 1094,
            VIEW_MESSAGE_TYPE = 1095,
            CREATE_MESSAGE_TYPE = 1096,
            EDIT_MESSAGE_TYPE = 1097,
            UPDATE_STATUS_MESSAGE_TYPE = 1098,
            VIEW_SKIN_PACKAGE_TYPE = 1099,
            CREATE_SKIN_PACKAGE_TYPE = 1100,
            EDIT_SKIN_PACKAGE_TYPE = 1101,
            DELETE_SKIN_PACKAGE_TYPE = 1102,
            VIEW_SKIN_PACKAGE_TEMPLATE = 1103,
            CREATE_SKIN_PACKAGE_TEMPLATE = 1104,
            EDIT_SKIN_PACKAGE_TEMPLATE = 1105,
            DELETE_SKIN_PACKAGE_TEMPLATE = 1106,
            VIEW_SKIN_PACKAGE_BACKGROUND = 1107,
            CREATE_SKIN_PACKAGE_BACKGROUND = 1108,
            EDIT_SKIN_PACKAGE_BACKGROUND = 1109,
            DELETE_SKIN_PACKAGE_BACKGROUND = 1110,
            VIEW_EVENT_TYPE = 1111,
            CREATE_EVENT_TYPE = 1112,
            EDIT_EVENT_TYPE = 1113,
            DELETE_EVENT_TYPE = 1114,
            VIEW_NOTIFICATION_TARGET = 1115,
            EDIT_NOTIFICATION_TARGET = 1116,
            VIEW_SERVICE_CATEGORY = 2067,
            CREATE_SERVICE_CATEGORY = 2068,
            EDIT_SERVICE_CATEGORY = 2069,
            DELETE_SERVICE_CATEGORY = 2070,
            CREATE_BOOKING_SERVICE = 2071,
        }
    }
}
