namespace Eagle.Core.Settings
{
    public class ModuleSetting
    {
        public const string APPLICATION = "APPLICATION";
        public const string EXTENSIONS = "EXTENSIONS";
        public const string HOST_LANGUAGES = "HOST_LANGUAGES";
        public const string EVENTS = "EVENTS";
        public const string HOSTMODULES = "HOSTMODULES";
        public const string DASHBOARD = "DASHBOARD";
        public const string USER_ACCOUNTS = "USER_ACCOUNTS";
        public const string SECURITY_ROLES = "SECURITY_ROLES";
        public const string PAGES = "PAGES";
        public const string TAXONOMY = "TAXONOMY";
        public const string FILE_MANAGER = "FILE_MANAGER";
        public const string PERMISSIONS = "PERMISSIONS";
        public const string CONTENT_TYPES = "CONTENT_TYPES";
        public const string CONTENT_ITEMS = "CONTENT_ITEMS";
        public const string MEDIA = "MEDIA";
        public const string VENDORS = "VENDORS";
        public const string GROUP_INFORMATION = "GROUP_INFORMATION";
        public const string NEWS = "NEWS";
        public const string SKIN_PACKAGE = "SKIN_PACKAGE";
        public const string SKIN_PACKAGE_TEMPLATE = "SKIN_PACKAGE_TEMPLATE";
        public const string BACKGROUND = "BACKGROUND";
        public const string AUDIO = "AUDIO";
        public const string VIDEO = "VIDEO";
        public const string MEDIA_TYPE = "MEDIA_TYPE";
        public const string DISCOUNTS = "DISCOUNTS";
        public const string DEDUCTIONS = "DEDUCTIONS";
        public const string VIEW = "VIEW";
        public const string HOST = "HOST";
        public const string COMMON_SYSTEM = "COMMON_SYSTEM";
        public const string SHOP_CART_SYSTEM = "SHOP_CART_SYSTEM";
        public const string NEWS_EVENTS = "NEWS_EVENTS";
        public const string NOTIFICATION_TARGET = "NOTIFICATION_TARGET";
        public const string MANUFACTURER_MANAGEMENT = "MANUFACTURER_MANAGEMENT";
        public const string PORTALS = "PORTALS";
        public const string PRODUCT_CATEGORIES = "PRODUCT_CATEGORIES";
        public const string PRODUCT_TYPES = "PRODUCT_TYPES";
        public const string TAXES = "TAXES";
        public const string MANUFACTURER_CATEGORIES = "MANUFACTURER_CATEGORIES";
        public const string MANUFACTURERS = "MANUFACTURERS";
        public const string SEO = "SEO";
        public const string BANNERS = "BANNERS";
        public const string BANNER_POSITIONS = "BANNER_POSITIONS";
        public const string CUSTOMERS = "CUSTOMERS";
        public const string MEDIA_TOPIC = "MEDIA_TOPIC";
        public const string GALLERY = "GALLERY";
        public const string GALLERY_TOPIC = "GALLERY_TOPIC";
        public const string GALLERY_COLLECTION = "GALLERY_COLLECTION";
        public const string GALLERY_FILES = "GALLERY_FILES";
        public const string MEDIA_ALBUM = "MEDIA_ALBUM";
        public const string MEDIA_ARTIST = "MEDIA_ARTIST";
        public const string MEDIA_COMPOSER = "MEDIA_COMPOSER";
        public const string MEDIA_PLAYLIST = "MEDIA_PLAYLIST";
        public const string ARTICLE_COMMENT = "ARTICLE_COMMENT";
        public const string FRIENDLY_URL_ROUTER = "FRIENDLY_URL_ROUTER";
        public const string SERVICE_PACK_DURATION = "SERVICE_PACK_DURATION";
        public const string NEWS_CATEGORIES = "NEWS_CATEGORIES";
        public const string ORDERS = "ORDERS";
        public const string SHIPPING = "SHIPPING";
        public const string SHIPPING_METHOD = "SHIPPING_METHOD";
        public const string SHIPPINGRATES = "SHIPPINGRATES";
        public const string SHIPPINGCARRIERS = "SHIPPINGCARRIERS";
        public const string CUSTOMER_ACOUNT = "CUSTOMER_ACOUNT";
        public const string CUSTOMER_TYPE = "CUSTOMER_TYPE";
        public const string PRODUCTS = "PRODUCTS";
        public const string PRODUCTCOMMENTS = "PRODUCTCOMMENTS";
        public const string TOOLS = "TOOLS";
        public const string HOST_ACCOUNTS = "HOST_ACCOUNTS";
        public const string SITE_SETTING = "SITE_SETTING";
        public const string SKIN_PACKAGE_BACKGROUND = "SKIN_PACKAGE_BACKGROUND";
        public const string DASHBOARD_MANAGER = "DASHBOARD_MANAGER";
        public const string MODULE_MANAGEMENTS = "MODULE_MANAGEMENTS";
        public const string LINKCATEGOIES = "LINKCATEGOIES";
        public const string LINKURL = "LINKURL";
        public const string MENU = "MENU";
        public const string MENUTYPE = "MENUTYPE";
        public const string LINKS = "LINKS";
        public const string TOPPANE = "TOPPANE";
        public const string RIGHTPANE = "RIGHTPANE";
        public const string BOTOMPANE = "BOTOMPANE";
        public const string LEFTPANE = "LEFTPANE";
        public const string CONTENTPANE = "CONTENTPANE";
        public const string MENU_OPTIONS = "MENU_OPTIONS";
        public const string EMAIL_SERVER_PROVIDERS = "EMAIL_SERVER_PROVIDERS";
        public const string MESSAGE_TYPE = "MESSAGE_TYPE";
        public const string EMAIL = "EMAIL";
        public const string EMAIL_TEMPLATES = "EMAIL_TEMPLATES";
        public const string MENUS = "MENUS";
        public const string NOTIFICATION_SENDER = "NOTIFICATION_SENDER";
        public const string HOST_USERS = "HOST_USERS";
        public const string EVENT_TYPE = "EVENT_TYPE";
        public const string HOST_MENU = "HOST_MENU";
        public const string HOST_MENU_TYPE = "HOST_MENU_TYPE";
        public const string HOST_MENU_OPTION = "HOST_MENU_OPTION";
        public const string HOST_MENUS = "HOST_MENUS";
        public const string ADMIN_MENU = "ADMIN_MENU";
        public const string SKIN_LAYOUT = "SKIN_LAYOUT";
        public const string ROLE_GROUPS = "ROLE_GROUPS";
        public const string HOTNEWS = "HOTNEWS";
        public const string LAST_NEWS = "LAST_NEWS";
        public const string ADVERTISEMENT = "ADVERTISEMENT";
        public const string ROLE_GROUPS_RIGHT = "ROLE_GROUPS_RIGHT";
        public const string TOP_HOT_NEWS = "TOP_HOT_NEWS";
        public const string SYSTEM_ADMINISTRATION = "SYSTEM_ADMINISTRATION";
        public const string HOST_PAGES = "HOST_PAGES";
        public const string PORTAL_PAGES = "PORTAL_PAGES";
        public const string SITE_USER_MANAGER = "SITE_USER_MANAGER";
        public const string PORTAL_MANAGER = "PORTAL_MANAGER";
        public const string HOST_SETTING = "HOST_SETTING";
        public const string ADD_MODULE_TO_TAB = "ADD_MODULE_TO_TAB";
        public const string HUMAN_RESOURCE = "HUMAN_RESOURCE";
        public const string RECRUITMENT = "RECRUITMENT";
        public const string PAYROLL = "PAYROLL";
        public const string TIMESHEET = "TIMESHEET";
        public const string TRAINING = "TRAINING";
        public const string INSURANCE = "INSURANCE";
        public const string TERMINATION = "TERMINATION";
        public const string SECURITY_INSURANCE = "SECURITY_INSURANCE";
        public const string EMPLOYEE = "EMPLOYEE";
        public const string NOTIFICATION_TYPE = "NOTIFICATION_TYPE";
        public const string COMPANY = "COMPANY";
        public const string MEDIA_AUDIO = "MEDIA_AUDIO";
        public const string MEDIA_VIDEO = "MEDIA_VIDEO";
        public const string PRODUCT_DISCOUNT = "PRODUCT_DISCOUNT";
        public const string CURRENCY = "CURRENCY";
        public const string DOCUMENT_FOLDER = "DOCUMENT_FOLDER";
        public const string DOCUMENT_FILE = "DOCUMENT_FILE";
        public const string BOOKING_SERVICE = "BOOKING_SERVICE";
        public const string SERVICE_BOOKING = "SERVICE_BOOKING";
        public const string SERVICE_DISCOUNT = "SERVICE_DISCOUNT";
        public const string SERVICE_PACK = "SERVICE_PACK";
        public const string JOB_POSITION = "JOB_POSITION";
        public const string CONTRACT = "CONTRACT";
        public const string BOOKING_CALENDAR = "BOOKING_CALENDAR";
        public const string SKIN_PACKAGE_TYPE = "SKIN_PACKAGE_TYPE";
        public const string SERVICE_CATEGORY = "SERVICE_CATEGORY";
    }

    public enum ModuleSettingType
    {
        APPLICATION = 1,
        EXTENSIONS = 2,
        HOST_LANGUAGES = 3,
        EVENTS = 4,
        HOSTMODULES = 5,
        DASHBOARD = 6,
        USER_ACCOUNTS = 7,
        SECURITY_ROLES = 8,
        PAGES = 9,
        TAXONOMY = 10,
        FILE_MANAGER = 11,
        PERMISSIONS = 12,
        CONTENT_TYPES = 13,
        CONTENT_ITEMS = 14,
        MEDIA = 15,
        VENDORS = 16,
        GROUP_INFORMATION = 17,
        NEWS = 18,
        SKIN_PACKAGE = 19,
        SKIN_PACKAGE_TEMPLATE = 20,
        BACKGROUND = 21,
        AUDIO = 22,
        VIDEO = 23,
        MEDIA_TYPE = 24,
        DISCOUNTS = 25,
        DEDUCTIONS = 26,
        VIEW = 27,
        HOST = 28,
        COMMON_SYSTEM = 29,
        SHOP_CART_SYSTEM = 30,
        NEWS_EVENTS = 31,
        NOTIFICATION_TARGET = 32,
        MANUFACTURER_MANAGEMENT = 33,
        PORTALS = 34,
        PRODUCT_CATEGORIES = 35,
        PRODUCT_TYPES = 36,
        TAXES = 37,
        MANUFACTURER_CATEGORIES = 38,
        MANUFACTURERS = 39,
        SEO = 40,
        BANNERS = 41,
        BANNER_POSITIONS = 42,
        CUSTOMERS = 43,
        MEDIA_TOPIC = 44,
        GALLERY = 45,
        GALLERY_TOPIC = 46,
        GALLERY_COLLECTION = 47,
        GALLERY_FILES = 48,
        MEDIA_ALBUM = 49,
        MEDIA_ARTIST = 50,
        MEDIA_COMPOSER = 51,
        MEDIA_PLAYLIST = 52,
        ARTICLE_COMMENT = 53,
        FRIENDLY_URL_ROUTER = 54,
        SERVICE_PACK_DURATION = 55,
        NEWS_CATEGORIES = 56,
        ORDERS = 57,
        SHIPPING = 58,
        SHIPPING_METHOD = 59,
        SHIPPINGRATES = 60,
        SHIPPINGCARRIERS = 61,
        CUSTOMER_ACOUNT = 62,
        CUSTOMER_TYPE = 63,
        PRODUCTS = 64,
        PRODUCTCOMMENTS = 65,
        TOOLS = 66,
        HOST_ACCOUNTS = 67,
        SITE_SETTING = 68,
        SKIN_PACKAGE_BACKGROUND = 69,
        DASHBOARD_MANAGER = 70,
        MODULE_MANAGEMENTS = 71,
        LINKCATEGOIES = 72,
        LINKURL = 73,
        MENU = 74,
        MENUTYPE = 75,
        LINKS = 76,
        TOPPANE = 77,
        RIGHTPANE = 78,
        BOTOMPANE = 79,
        LEFTPANE = 80,
        CONTENTPANE = 81,
        MENU_OPTIONS = 82,
        EMAIL_SERVER_PROVIDERS = 83,
        MESSAGE_TYPE = 84,
        EMAIL = 85,
        EMAIL_TEMPLATES = 86,
        MENUS = 87,
        NOTIFICATION_SENDER = 88,
        HOST_USERS = 89,
        EVENT_TYPE = 90,
        HOST_MENU = 91,
        HOST_MENU_TYPE = 92,
        HOST_MENU_OPTION = 93,
        HOST_MENUS = 94,
        ADMIN_MENU = 95,
        SKIN_LAYOUT = 96,
        ROLE_GROUPS = 97,
        HOTNEWS = 98,
        LAST_NEWS = 99,
        ADVERTISEMENT = 100,
        ROLE_GROUPS_RIGHT = 101,
        TOP_HOT_NEWS = 102,
        SYSTEM_ADMINISTRATION = 103,
        HOST_PAGES = 104,
        PORTAL_PAGES = 105,
        SITE_USER_MANAGER = 106,
        PORTAL_MANAGER = 107,
        HOST_SETTING = 108,
        ADD_MODULE_TO_TAB = 109,
        HUMAN_RESOURCE = 110,
        RECRUITMENT = 111,
        PAYROLL = 112,
        TIMESHEET = 114,
        TRAINING = 116,
        INSURANCE = 117,
        TERMINATION = 118,
        SECURITY_INSURANCE = 120,
        EMPLOYEE = 121,
        NOTIFICATION_TYPE = 122,
        COMPANY = 123,
        MEDIA_AUDIO = 124,
        MEDIA_VIDEO = 126,
        PRODUCT_DISCOUNT = 127,
        CURRENCY = 128,
        DOCUMENT_FOLDER = 129,
        DOCUMENT_FILE = 130,
        BOOKING_SERVICE = 131,
        SERVICE_BOOKING = 1131,
        SERVICE_DISCOUNT = 1132,
        SERVICE_PACK = 1133,
        JOB_POSITION = 1134,
        CONTRACT = 1135,
        BOOKING_CALENDAR = 1136,
        SKIN_PACKAGE_TYPE = 1137,
        SERVICE_CATEGORY = 2131,
    }
}
