CREATE TABLE [Sales].[Customer] (
    [VendorId]             INT              NULL,
    [CustomerId]           INT              IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CustomerTypeId]       INT              NOT NULL,
    [CustomerNo]           UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL,
    [CardNo]               NVARCHAR (20)    NULL,
    [CustomerName]         NVARCHAR (200)   NOT NULL,
    [ContactName]          NVARCHAR (200)   NULL,
    [IDCardNo]             NVARCHAR (20)    NULL,
    [PassPortNo]           NVARCHAR (50)    NULL,
    [TaxCode]              NVARCHAR (50)    NULL,
    [BirthDay]             DATETIME         NULL,
    [Address]              NVARCHAR (250)   NOT NULL,
    [Country]              NVARCHAR (50)    NULL,
    [PostalCode]           NVARCHAR (50)    NULL,
    [Phone]                NVARCHAR (20)    NULL,
    [Mobile]               NVARCHAR (30)    NULL,
    [Fax]                  NVARCHAR (50)    NULL,
    [Email]                NVARCHAR (150)   NOT NULL,
    [PasswordHash]         VARCHAR (500)    NOT NULL,
    [PasswordSalt]         VARCHAR (30)     NOT NULL,
    [Verified]             BIT              NOT NULL,
    [IsActive]             BIT              NULL,
    [Ip]                   VARCHAR (30)     NULL,
    [LastUpdatedIp]        VARCHAR (30)     NULL,
    [CreatedDate]          DATETIME         NULL,
    [LastModifiedDate]     DATETIME         NULL,
    [CreatedByUserId]      UNIQUEIDENTIFIER NULL,
    [LastModifiedByUserId] UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK__Customer__A4AE64D8682063BF] PRIMARY KEY CLUSTERED ([CustomerId] ASC)
);

