using System.Collections.Generic;
using Eagle.Resources;

namespace Eagle.Services.Dtos.Common
{
    public static class ErrorMessage
    {
        public static IDictionary<ErrorCode, string> Messages;

        static ErrorMessage()
        {
            Messages = new Dictionary<ErrorCode, string>
            {
                {ErrorCode.Error, LanguageResource.Error},
                {ErrorCode.Validation, LanguageResource.Validation},
                {ErrorCode.NoPermission, LanguageResource.NoPermission},
                {ErrorCode.NoAccessData, LanguageResource.NoAccessData},
                {ErrorCode.NullReference, LanguageResource.NullReference},
                {ErrorCode.InvalidMessageId, LanguageResource.InvalidMessageId},
                {ErrorCode.InvalidLabel, LanguageResource.InvalidLabel},
                {ErrorCode.InvalidPriority, LanguageResource.InValidPriority},
                {ErrorCode.InvalidTemplateId, LanguageResource.InvalidTemplateId},
                {ErrorCode.InvalidNotificationTypeId, LanguageResource.InvalidNotificationTypeId},
                {ErrorCode.InvalidMemberId, LanguageResource.InvalidMemberId},
                {ErrorCode.InvalidNetworkId, LanguageResource.InvalidNetworkId},
                {ErrorCode.InvalidNetworkDescription, LanguageResource.InvalidNetworkDescription},
                {ErrorCode.InvalidWebsiteUrl, LanguageResource.InvalidWebsiteUrl},
                {ErrorCode.InvalidWebsiteUrlBase, LanguageResource.InvalidWebsiteUrlBase},
                {ErrorCode.InvalidExtraInfo, LanguageResource.InvalidExtraInfo},
                {ErrorCode.InvalidVersion, LanguageResource.InvalidVersion},
                {ErrorCode.InvalidTimeZone, LanguageResource.InvalidTimeZone},
                {ErrorCode.InvalidAddress, LanguageResource.InvalidAddress},
                {ErrorCode.InvalidComment, LanguageResource.InvalidComment},
                {ErrorCode.InvalidOwner, LanguageResource.InvalidOwner},
                {ErrorCode.InvalidContentSummary, LanguageResource.InvalidContentSummary},
                {ErrorCode.InvalidStartDate, LanguageResource.InvalidStartDate},
                {ErrorCode.InvalidEndDate, LanguageResource.InvalidEndDate},
                {ErrorCode.InvalidTitle, LanguageResource.InvalidTitle},
                {ErrorCode.InvalidDescription, LanguageResource.InvalidDescription},
                {ErrorCode.InvalidStatus, LanguageResource.InvalidStatus},
                {ErrorCode.InvalidParentId, LanguageResource.InvalidParentId},
                {ErrorCode.InvalidTypeName, LanguageResource.InvalidTypeName},
                {ErrorCode.InvalidScheduleId, LanguageResource.InvalidScheduleId},
                {ErrorCode.NotFoundForSite, LanguageResource.NotFoundForSite},
                {ErrorCode.NotFoundForServiceRequest, LanguageResource.NotFoundForServiceRequest},
                {ErrorCode.NotFoundForVariationRequest, LanguageResource.NotFoundForVariationRequest},
                {ErrorCode.NotFoundForSchedule, LanguageResource.NotFoundForSchedule},
                {ErrorCode.NullReferenceForParentId, LanguageResource.NullReferenceForParentId},
                {ErrorCode.DuplicateName, LanguageResource.DuplicateName},
                {ErrorCode.DuplicateData, LanguageResource.DuplicateData},
                {ErrorCode.NotFoundForClient, LanguageResource.NotFoundForClient},
                {ErrorCode.NotFoundForClientBySite, LanguageResource.NotFoundForClientBySite},
                {ErrorCode.NotFoundForScheduleRequest, LanguageResource.NotFoundForScheduleRequest},

                {ErrorCode.InvalidSubject,LanguageResource.InvalidSubject},
                {ErrorCode.InvalidTemplateName, LanguageResource.InvalidTemplateName},
                {ErrorCode.InvalidTemplateContent, LanguageResource.InvalidTemplateContent},
                {ErrorCode.UnauthorizedAsccessError,  LanguageResource.UnauthorizedAsccessError},
                {ErrorCode.NotFoundForServiceRequestEntry, LanguageResource.NotFoundForServiceRequestEntry},
                {ErrorCode.NotFoundForUserId, LanguageResource.NotFoundForUserId},
                {ErrorCode.NotFoundForUser, LanguageResource.NotFoundForUser},
                {ErrorCode.NotFoundForMailGroup, LanguageResource.NotFoundForMailGroup},
                {ErrorCode.NotFoundForMailSystem, LanguageResource.NotFoundForMailSystem},
                {ErrorCode.NullReferenceForMessageQueueEntry, LanguageResource.NullReferenceForMessageQueueEntry},

                {ErrorCode.InvalidFrom, LanguageResource.InvalidFrom},
                {ErrorCode.InvalidTo, LanguageResource.InvalidTo},
                {ErrorCode.InvalidBody, LanguageResource.InvalidBody},
                {ErrorCode.NotFoundAppSetting,  LanguageResource.NotFoundAppSetting},
                {ErrorCode.InvalidBannerTypeId, LanguageResource.InvalidBannerTypeId},
                {ErrorCode.InvalidBannerPositionId, LanguageResource.InvalidBannerPositionId},
                {ErrorCode.InvalidName, LanguageResource.InvalidName},
                {ErrorCode.NotFoundForMessageTemplate, LanguageResource.NotFoundForMessageTemplate},
                {ErrorCode.NotFoundForRoleGroup, LanguageResource.NotFoundForRoleGroup},
                {ErrorCode.InvalidTagName, LanguageResource.InvalidTagName},

                {ErrorCode.NotFoundTag, LanguageResource.NotFoundTag},
                {ErrorCode.InvalidTagType, LanguageResource.InvalidTagType},
                {ErrorCode.NotFoundTagType, LanguageResource.NotFoundTagType},
                {ErrorCode.NotFoundData, LanguageResource.NotFoundData},
                {ErrorCode.NotFoundEntry, LanguageResource.NotFoundEntry},
                {ErrorCode.InvalidId, LanguageResource.InvalidId},
                {ErrorCode.InvalidSkinTypeId, LanguageResource.InvalidSkinTypeId},
                {ErrorCode.ExistedData, LanguageResource.ExistedData},
                {ErrorCode.ExistedEmail, LanguageResource.ExistedEmail},
                {ErrorCode.InvalidUserName, LanguageResource.InvalidUserName},
                {ErrorCode.InvalidPassword, LanguageResource.InvalidPassword},
                {ErrorCode.InvalidPasswordSalt, LanguageResource.InvalidPasswordSalt},
                {ErrorCode.InvalidPasswordHash, LanguageResource.InvalidPasswordHash},

                {ErrorCode.InvalidSettingName, LanguageResource.InvalidSettingName},
                {ErrorCode.InvalidSettingValue, LanguageResource.InvalidSettingValue},
                {ErrorCode.NotFoundApplicationSetting, LanguageResource.NotFoundApplicationSetting},
                {ErrorCode.InvalidPhone, LanguageResource.InvalidPhone},
                {ErrorCode.InvalidAddressId, LanguageResource.InvalidAddressId},
                {ErrorCode.InvalidCurrencyName,LanguageResource.InvalidCurrencyName},
                {ErrorCode.NotFoundCurrency, LanguageResource.NotFoundCurrency},

                {ErrorCode.InvalidCurrencyCode, LanguageResource.InvalidCurrencyCode},
                {ErrorCode.InvalidFromCurrencyCode, LanguageResource.InvalidFromCurrencyCode},
                {ErrorCode.InvalidToCurrencyCode, LanguageResource.InvalidToCurrencyCode},
                {ErrorCode.NotFoundCurrencyRateEntry, LanguageResource.NotFoundCurrencyRateEntry},
                {ErrorCode.InvalidCurrencyRateDate, LanguageResource.InvalidCurrencyRateDate},
                {ErrorCode.InvalidAverageRate, LanguageResource.InvalidAverageRate},
                {ErrorCode.InvalidEndOfDayRate, LanguageResource.InvalidEndOfDayRate},
                {ErrorCode.NotFoundCurrencyRate, LanguageResource.NotFoundCurrencyRate},
                {ErrorCode.InvalidCategoryCode, LanguageResource.InvalidCategoryCode},

                {ErrorCode.DuplicateAttribute, LanguageResource.DuplicateAttribute},
                {ErrorCode.DuplicateAttributeName, LanguageResource.DuplicateAttributeName},
                {ErrorCode.InvalidAttributeId, LanguageResource.InvalidAttributeId},
                {ErrorCode.InvalidAttributeName, LanguageResource.InvalidAttributeName},
                {ErrorCode.NotFoundAttribute, LanguageResource.NotFoundAttribute},
                {ErrorCode.NotFoundOption, LanguageResource.NotFoundOption},
                {ErrorCode.InvalidOptionId, LanguageResource.InvalidOptionId},
                {ErrorCode.InvalidOptionName, LanguageResource.InvalidOptionName},
                {ErrorCode.InvalidOptionValue, LanguageResource.InvalidOptionValue},
                {ErrorCode.InvalidFileName, LanguageResource.InvalidFileName},
                {ErrorCode.InvalidFolder, LanguageResource.InvalidFolder},

                {ErrorCode.InvalidDomainKey, LanguageResource.InvalidDomainKey},
                {ErrorCode.InvalidDomainType, LanguageResource.InvalidDomainType},
                {ErrorCode.InvalidNewsCategoryStatus, LanguageResource.InvalidNewsCategoryStatus},
                {ErrorCode.InvalidNewsStatus, LanguageResource.InvalidNewsStatus},
                {ErrorCode.NotFoundForNews, LanguageResource.NotFoundForNews},
                {ErrorCode.NotFoundForNewsCategory, LanguageResource.NotFoundForNewsCategory},
                {ErrorCode.InvaliHeadline, LanguageResource.InvaliHeadline},
                {ErrorCode.InvalidCategoryId, LanguageResource.InvalidCategoryId},

                {ErrorCode.InvalidCategoryName, LanguageResource.InvalidCategoryName},
                {ErrorCode.InvalidCommentName, LanguageResource.InvalidCommentName},
                {ErrorCode.InvalidCommentText, LanguageResource.InvalidCommentText},
                {ErrorCode.InvalidEmail, LanguageResource.InvalidEmail},
                {ErrorCode.NotFoundForMenuPermission, LanguageResource.NotFoundForMenuPermission},
                {ErrorCode.NotFoundForApplication, LanguageResource.NotFoundForApplication},
                {ErrorCode.InvalidModuleId, LanguageResource.InvalidModuleId},
                {ErrorCode.InvalidRoleId, LanguageResource.InvalidRoleId},
                {ErrorCode.NotFoundCapability, LanguageResource.NotFoundCapability},
                {ErrorCode.InvalidLanguageCode, LanguageResource.InvalidLanguageCode},
                {ErrorCode.NullLanguageCode, LanguageResource.NullLanguageCode},
                {ErrorCode.NotFoundCurrencyEntry, LanguageResource.NotFoundCurrencyEntry},
                {ErrorCode.NotFoundForDocumentFile, LanguageResource.NotFoundForDocumentFile},
                {ErrorCode.NotFoundForDocumentFolder, LanguageResource.NotFoundForDocumentFolder},
                {ErrorCode.NotFoundHttpPostedFile, LanguageResource.NotFoundHttpPostedFile},

                {ErrorCode.NotFoundNewsEntry, LanguageResource.NotFoundNewsEntry},
                {ErrorCode.NotFoundNewsCategoryEntry, LanguageResource.NotFoundNewsEntry},
                {ErrorCode.NotFoundNewsCommentEntry, LanguageResource.NotFoundNewsEntry},

                {ErrorCode.NotFoundBannerEntry, LanguageResource.NotFoundBannerEntry},
                {ErrorCode.NotFoundBannerPositionEntry, LanguageResource.NotFoundBannerPositionEntry},
                {ErrorCode.NotFoundBannerSearchEntry, LanguageResource.NotFoundBannerSearchEntry},
                {ErrorCode.NotFoundBannerTypeEntry, LanguageResource.NotFoundBannerTypeEntry},

                {ErrorCode.DuplicateDocumentFolder, LanguageResource.DuplicateDocumentFolder},
                {ErrorCode.NotFoundDocumentFileEntry, LanguageResource.NotFoundDocumentFileEntry},
                {ErrorCode.NotFoundDirectory, LanguageResource.NotFoundDirectory},
                {ErrorCode.DuplicateTitle, LanguageResource.DuplicateTitle},
                {ErrorCode.DuplicateCompanyName, LanguageResource.DuplicateCompanyName},
                {ErrorCode.DuplicateBranchName, LanguageResource.DuplicateBranchName},
                {ErrorCode.DuplicateDepartmentName, LanguageResource.DuplicateDepartmentName},
                {ErrorCode.DuplicateCategoryName, LanguageResource.DuplicateCategoryName},
                {ErrorCode.DuplicateBannerTitle, LanguageResource.DuplicateBannerTitle},
                {ErrorCode.NotFoundBanner, LanguageResource.NotFoundBanner},
                {ErrorCode.DuplicateBannerPositionName, LanguageResource.DuplicateBannerPositionName},
                {ErrorCode.NotFoundBannerPostion, LanguageResource.NotFoundBannerPostion},
                {ErrorCode.NotFoundUser, LanguageResource.NotFoundUser},
                {ErrorCode.NotFoundRole, LanguageResource.NotFoundRole},
                {ErrorCode.NotFoundPage, LanguageResource.NotFoundPage},
                {ErrorCode.NotFoundLanguage, LanguageResource.NotFoundLanguage},
                {ErrorCode.NotFoundApplication, LanguageResource.NotFoundApplication},
                {ErrorCode.NullFileName, LanguageResource.NullFileName},
                {ErrorCode.InvalidFolderId, LanguageResource.InvalidFolderId},
                {ErrorCode.NullPageName, LanguageResource.NullPageName},
                {ErrorCode.InvalidPageName, LanguageResource.InvalidPageName},
                {ErrorCode.DuplicatePageName, LanguageResource.DuplicatePageName},

                {ErrorCode.NullModuleEditEntry, LanguageResource.NullModuleEditEntry},
                {ErrorCode.NullPasswordSalt, LanguageResource.NullPasswordSalt},
                {ErrorCode.NullModuleTitle, LanguageResource.NullModuleTitle},
                {ErrorCode.DuplicateModuleTitle, LanguageResource.DuplicateModuleTitle},
                {ErrorCode.NullFirstName,  LanguageResource.NullFirstName},
                {ErrorCode.NullLastName,  LanguageResource.NullLastName},
                {ErrorCode.NullPhone,  LanguageResource.NullPhone},
                {ErrorCode.InvalidJoinedDate,  LanguageResource.InvalidJoinedDate},
                {ErrorCode.InvalidPositionId, LanguageResource.InvalidPositionId},
                {ErrorCode.NullPositionId, LanguageResource.NullPositionId},
                {ErrorCode.NullCompanyId,  LanguageResource.NullCompanyId},
                {ErrorCode.ToDateMustBeGreaterThanFromDate,  LanguageResource.ToDateMustBeGreaterThanFromDate},
                {ErrorCode.InvalidExpiredDate,  LanguageResource.InvalidExpiredDate},
                {ErrorCode.InvalidItemKey, LanguageResource.InvalidItemKey},
                {ErrorCode.NullTitle,  LanguageResource.NullTitle},
                {ErrorCode.NotFoundUserId,  LanguageResource.NotFoundUserId},
                {ErrorCode.NullUserName,  LanguageResource.NullUserName},

                {ErrorCode.NotFoundCompanyEntry, LanguageResource.NotFoundCompanyEntry},
                {ErrorCode.NotFoundCompany, LanguageResource.NotFoundCompany},
                {ErrorCode.InvalidCompanyId, LanguageResource.InvalidCompanyId},
                {ErrorCode.InvalidCompanyName, LanguageResource.InvalidCompanyName},
                {ErrorCode.NotFoundBranchEntry, LanguageResource.NotFoundBranchEntry},
                {ErrorCode.InvalidBranchId, LanguageResource.InvalidBranchId},
                {ErrorCode.InvalidBranchName, LanguageResource.InvalidBranchName},
                {ErrorCode.NotFoundDepartmentEntry, LanguageResource.NotFoundDepartmentEntry},
                {ErrorCode.NotFoundDepartment, LanguageResource.NotFoundDepartment},
                {ErrorCode.InvalidDepartmentId, LanguageResource.InvalidDepartmentId},
                {ErrorCode.InvalidDepartmentName,LanguageResource.InvalidDepartmentName},
                {ErrorCode.NotFoundUserEntry, LanguageResource.NotFoundUserEntry},

                {ErrorCode.NotFoundCustomerEntry, LanguageResource.NotFoundCustomerEntry},
                {ErrorCode.NotFoundCustomer, LanguageResource.NotFoundCustomer},
                {ErrorCode.DuplicateCustomerName, LanguageResource.DuplicateCustomerName},
                {ErrorCode.InvalidCustomerName, LanguageResource.InvalidCustomerName},
                {ErrorCode.InvalidCardNo, LanguageResource.InvalidCardNo},
                {ErrorCode.ExistedPhone, LanguageResource.ExistedPhone},
                {ErrorCode.InvalidPostalCode, LanguageResource.InvalidPostalCode},
                {ErrorCode.InvalidFax, LanguageResource.InvalidFax},
                {ErrorCode.InvalidFirstName, LanguageResource.InvalidFirstName},
                {ErrorCode.InvalidLastName, LanguageResource.InvalidLastName},

                {ErrorCode.NotFoundCustomerTypeEntry, LanguageResource.NotFoundCustomerTypeEntry},
                {ErrorCode.NotFoundCustomerType, LanguageResource.NotFoundCustomerType},
                {ErrorCode.DuplicateCustomerTypeName, LanguageResource.DuplicateCustomerTypeName},
                {ErrorCode.InvalidCustomerTypeName, LanguageResource.InvalidCustomerTypeName},
                {ErrorCode.InvalidCustomerTypeId, LanguageResource.InvalidCustomerTypeId},

                {ErrorCode.NotFoundProductEntry, LanguageResource.NotFoundProductEntry},
                {ErrorCode.NotFoundProduct, LanguageResource.NotFoundProduct},
                {ErrorCode.DuplicateProduct, LanguageResource.DuplicateProduct},
                {ErrorCode.InvalidProductId, LanguageResource.InvalidProductId},
                {ErrorCode.InvalidProductNo, LanguageResource.InvalidProductNo},
                {ErrorCode.InvalidProductName, LanguageResource.InvalidProductName},
                {ErrorCode.InvalidQuantity, LanguageResource.InvalidQuantity},
                {ErrorCode.InvalidPrice, LanguageResource.InvalidPrice},
                {ErrorCode.InvalidUnitPrice, LanguageResource.InvalidUnitPrice},
                {ErrorCode.NullProductName, LanguageResource.NullProductName},
                {ErrorCode.ExistedOder, LanguageResource.ExistedOder},

                {ErrorCode.NotFoundProductCategoryEntry, LanguageResource.NotFoundProductCategoryEntry},
                {ErrorCode.NotFoundProductCategory, LanguageResource.NotFoundProductCategory},
                {ErrorCode.DuplicateProductCategoryName, LanguageResource.DuplicateProductCategoryName},
                {ErrorCode.InvalidProductCategoryId, LanguageResource.InvalidProductCategoryId},
                {ErrorCode.InvalidProductCategoryCode, LanguageResource.InvalidProductCategoryCode},

                {ErrorCode.NotFoundProductTypeEntry, LanguageResource.NotFoundProductTypeEntry},
                {ErrorCode.NotFoundProductType, LanguageResource.NotFoundProductType},
                {ErrorCode.InvalidProductTypeId, LanguageResource.InvalidProductTypeId},
                {ErrorCode.InvalidProductTypeName, LanguageResource.InvalidProductTypeName},
                {ErrorCode.NullReferenceForVendorProductTypeEntry, LanguageResource.NullReferenceForVendorProductTypeEntry},
                {ErrorCode.NotFoundVendorProductType, LanguageResource.NotFoundVendorProductType},
                {ErrorCode.DuplicateVendorProductType, LanguageResource.DuplicateVendorProductType},

                {ErrorCode.NotFoundProductTaxRateEntry, LanguageResource.NotFoundProductTaxRateEntry},
                {ErrorCode.NotFoundProductTaxRate, LanguageResource.NotFoundProductTaxRate},
                {ErrorCode.DuplicateProductTaxRateName, LanguageResource.DuplicateProductTaxRateName},
                {ErrorCode.DuplicateTaxRate, LanguageResource.DuplicateTaxRate},
                {ErrorCode.InvalidProductTaxRate, LanguageResource.InvalidProductTaxRate},
                {ErrorCode.InvalidProductTaxRateId, LanguageResource.InvalidProductTaxRateId},
                {ErrorCode.InvalidProductTaxRateName, LanguageResource.InvalidProductTaxRateName},
                {ErrorCode.NullProductTaxRate, LanguageResource.NullProductTaxRate},

                {ErrorCode.NotFoundProductAttributeEntry, LanguageResource.NotFoundProductAttributeEntry},
                {ErrorCode.NotFoundProductAttribute, LanguageResource.NotFoundProductAttribute},
                {ErrorCode.DuplicateProductAttribute, LanguageResource.DuplicateProductAttribute},
                {ErrorCode.DuplicateProductAttributeName, LanguageResource.DuplicateProductAttributeName},
                {ErrorCode.InvalidProductAttributeId, LanguageResource.InvalidProductAttributeId},
                {ErrorCode.InvalidProductAttributeName, LanguageResource.InvalidProductAttributeName},
                {ErrorCode.NullProductAttributeName, LanguageResource.NullProductAttributeName},

                {ErrorCode.NotFoundProductAttributeOptionEntry, LanguageResource.NotFoundProductAttributeOptionEntry},
                {ErrorCode.NotFoundProductAttributeOption, LanguageResource.NotFoundProductAttributeOption},
                {ErrorCode.DuplicateProductAttributeOption, LanguageResource.DuplicateProductAttributeOption},
                {ErrorCode.InvalidProductAttributeOptionId, LanguageResource.InvalidProductAttributeOptionId},
                {ErrorCode.InvalidProductAttributeOptionName, LanguageResource.InvalidProductAttributeOptionName},
                {ErrorCode.InvalidProductAttributeOptionValue, LanguageResource.InvalidProductAttributeOptionValue},

                {ErrorCode.NotFoundProductCouponEntry, LanguageResource.NotFoundProductCouponEntry},
                {ErrorCode.NotFoundProductCoupon, LanguageResource.NotFoundProductCoupon},
                {ErrorCode.DuplicateProductCoupon, LanguageResource.DuplicateProductCoupon},
                {ErrorCode.InvalidProductCouponId, LanguageResource.InvalidProductCouponId},
                {ErrorCode.InvalidProductCouponName, LanguageResource.InvalidProductCouponName},

                {ErrorCode.NotFoundProductDiscountEntry, LanguageResource.NotFoundProductDiscountEntry},
                {ErrorCode.NotFoundProductDiscount, LanguageResource.NotFoundProductDiscount},
                {ErrorCode.DuplicateProductDiscount, LanguageResource.DuplicateProductDiscount},
                {ErrorCode.InvalidProductDiscountId, LanguageResource.InvalidProductDiscountId},
                {ErrorCode.InvalidDiscountRate, LanguageResource.InvalidDiscountRate},

                {ErrorCode.NotFoundProductFileEntry, LanguageResource.NotFoundProductFileEntry},
                {ErrorCode.NotFoundProductFile, LanguageResource.NotFoundProductFile},
                {ErrorCode.DuplicateProductFile, LanguageResource.DuplicateProductFile},
                {ErrorCode.InvalidProductFileId, LanguageResource.InvalidProductFileId},

                {ErrorCode.NotFoundProductRangeEntry, LanguageResource.NotFoundProductRangeEntry},
                {ErrorCode.NotFoundProductRange, LanguageResource.NotFoundProductRange},
                {ErrorCode.DuplicateProductRange, LanguageResource.DuplicateProductRange},
                {ErrorCode.InvalidProductRangeId, LanguageResource.InvalidProductRangeId},
                {ErrorCode.InvalidProductRangeCode, LanguageResource.InvalidProductRangeCode},
                {ErrorCode.InvalidProductRangeName, LanguageResource.InvalidProductRangeName},

                {ErrorCode.NotFoundProductVoteEntry, LanguageResource.NotFoundProductVoteEntry},
                {ErrorCode.NotFoundProductVote, LanguageResource.NotFoundProductVote},
                {ErrorCode.DuplicateProducVote, LanguageResource.DuplicateProducVote},
                {ErrorCode.InvalidProductVoteId, LanguageResource.InvalidProductVoteId},
                {ErrorCode.NullReferenceForPromotionEntry, LanguageResource.NullReferenceForPromotionEntry},
                {ErrorCode.NullReferenceForPromotion, LanguageResource.NullReferenceForPromotion},
                {ErrorCode.NotFoundPromotion, LanguageResource.NotFoundPromotion},
                {ErrorCode.DuplicatePromotion, LanguageResource.DuplicatePromotion},
                {ErrorCode.InvalidPromotionId, LanguageResource.InvalidPromotionId},
                {ErrorCode.InvalidPromotionValue, LanguageResource.InvalidPromotionValue},

                {ErrorCode.NotFoundOrderEntry, LanguageResource.NotFoundOrderEntry},
                {ErrorCode.InvalidCustomerNo, LanguageResource.InvalidCustomerNo},
                {ErrorCode.InvalidSubTotal, LanguageResource.InvalidSubTotal},
                {ErrorCode.InvalidTotalFees, LanguageResource.InvalidTotalFees},
                {ErrorCode.NotFoundOrder, LanguageResource.NotFoundOrder},
                {ErrorCode.InvalidOrderNo, LanguageResource.InvalidOrderNo},

                {ErrorCode.NotFoundOrderProductEntry, LanguageResource.NotFoundOrderProductEntry},
                {ErrorCode.NotFoundOrderProduct, LanguageResource.NotFoundOrderProduct},

                {ErrorCode.NotFoundManufacturerEntry, LanguageResource.NotFoundManufacturerEntry},
                {ErrorCode.NotFoundManufacturer, LanguageResource.NotFoundManufacturer},
                {ErrorCode.DuplicateManufacturerName, LanguageResource.DuplicateManufacturerName},
                {ErrorCode.InvalidManufacturerName, LanguageResource.InvalidManufacturerName},

                {ErrorCode.NotFoundManufacturerCategoryEntry, LanguageResource.NotFoundManufacturerCategoryEntry},
                {ErrorCode.NotFoundManufacturerCategory, LanguageResource.NotFoundManufacturerCategory},
                {ErrorCode.InvalidManufacturerCategoryId, LanguageResource.InvalidManufacturerCategoryId},
                {ErrorCode.InvalidManufacturerCategoryName, LanguageResource.InvalidManufacturerCategoryName},

                {ErrorCode.NotFoundTransactionMethodEntry, LanguageResource.NotFoundTransactionMethodEntry},
                {ErrorCode.NotFoundTransactionMethod, LanguageResource.NotFoundTransactionMethod},
                {ErrorCode.DuplicateTransactionMethodName, LanguageResource.DuplicateTransactionMethodName},
                {ErrorCode.InvalidTransactionMethodId, LanguageResource.InvalidTransactionMethodId},
                {ErrorCode.InvalidTransactionMethodName, LanguageResource.InvalidTransactionMethodName},

                {ErrorCode.NotFoundPaymentMethodEntry, LanguageResource.NotFoundPaymentMethodEntry},
                {ErrorCode.NotFoundPaymentMethod, LanguageResource.NotFoundPaymentMethod},
                {ErrorCode.DuplicatePaymentMethodName, LanguageResource.DuplicatePaymentMethodName},
                {ErrorCode.InvalidPaymentMethodId, LanguageResource.InvalidPaymentMethodId},
                {ErrorCode.InvalidPaymentMethodName, LanguageResource.InvalidPaymentMethodName},

                {ErrorCode.NotFoundVendorEntry, LanguageResource.NotFoundVendorEntry},
                {ErrorCode.NotFoundVendor, LanguageResource.NotFoundVendor},
                {ErrorCode.DuplicateVendorName, LanguageResource.DuplicateVendorName},
                {ErrorCode.InvalidVendorId, LanguageResource.InvalidVendorId},
                {ErrorCode.InvalidVendorName, LanguageResource.InvalidVendorName},

                {ErrorCode.NotFoundVendorProductDiscountEntry, LanguageResource.NotFoundVendorProductDiscountEntry},
                {ErrorCode.NotFoundVendorProductDiscount, LanguageResource.NotFoundVendorProductDiscount},
                {ErrorCode.DuplicateVendorProductDiscount, LanguageResource.DuplicateVendorProductDiscount},
                {ErrorCode.InvalidDiscountId, LanguageResource.InvalidDiscountId},

                {ErrorCode.NotFoundContentTypeEntry, LanguageResource.NotFoundContentTypeEntry},
                {ErrorCode.NotFoundContentType, LanguageResource.NotFoundContentType},
                {ErrorCode.NullContentTypeEntry, LanguageResource.NullContentTypeEntry},
                {ErrorCode.DuplicateContentTypeName, LanguageResource.DuplicateContentTypeName},
                {ErrorCode.InvalidContentTypeId, LanguageResource.InvalidContentTypeId},
                {ErrorCode.InvalidContentTypeName, LanguageResource.InvalidContentTypeName},

                {ErrorCode.NotFoundContentItemEntry, LanguageResource.NotFoundContentItemEntry},
                {ErrorCode.NotFoundContentItem, LanguageResource.NotFoundContentItem},
                {ErrorCode.NullContentItemEntry, LanguageResource.NullContentItemEntry},
                {ErrorCode.NullContentItem, LanguageResource.NullContentItem},
                {ErrorCode.DuplicateContentItemName, LanguageResource.DuplicateContentItemName},
                {ErrorCode.InvalidContentItemId, LanguageResource.InvalidContentItemId},
                {ErrorCode.InvalidContentItemName, LanguageResource.InvalidContentItemName},

                {ErrorCode.DuplicateRoleName,  LanguageResource.DuplicateRoleName},
                {ErrorCode.InvalidGroupName,  LanguageResource.InvalidGroupName},
                {ErrorCode.DuplicateGroupName,  LanguageResource.DuplicateGroupName},
                {ErrorCode.NotFoundRoleEntry, LanguageResource.NotFoundRoleEntry},
                {ErrorCode.InvalidRoleName,  LanguageResource.InvalidRoleName},
                {ErrorCode.NotFoundRoleGroupEntry,  LanguageResource.NotFoundRoleGroupEntry},

                {ErrorCode.InvalidPermissionName, LanguageResource.InvalidPermissionName},
                {ErrorCode.DuplicatePermissionName, LanguageResource.DuplicatePermissionName},
                {ErrorCode.NotFoundPermissionEntry, LanguageResource.NotFoundPermissionEntry},
                {ErrorCode.NotFoundPermission, LanguageResource.NotFoundPermission},
                {ErrorCode.NullPagePermissionEntry, LanguageResource.NullPagePermissionEntry},
                {ErrorCode.NotFoundPagePermission, LanguageResource.NotFoundPagePermission},
                {ErrorCode.NullPageEntry, LanguageResource.NullPageEntry},
                {ErrorCode.NullPageRolePermissionEntry, LanguageResource.NullPageRolePermissionEntry},

                {ErrorCode.NotFoundLog, LanguageResource.NotFoundLog},
                {ErrorCode.NullModuleEntry, LanguageResource.NullModuleEntry},
                {ErrorCode.DuplicateModuleName, LanguageResource.DuplicateModuleName},
                {ErrorCode.NotFoundModule, LanguageResource.NotFoundModule},
                {ErrorCode.NotFoundModuleCapability, LanguageResource.NotFoundModuleCapability},
                {ErrorCode.NullModuleCapabilityEntry, LanguageResource.NullModuleCapabilityEntry},
                {ErrorCode.NotFoundModulePermission, LanguageResource.NotFoundModulePermission},

                {ErrorCode.NullMenuEntry, LanguageResource.NullMenuEntry},
                {ErrorCode.NullMenuEditEntry, LanguageResource.NullMenuEditEntry},
                {ErrorCode.NotFoundMenu, LanguageResource.NotFoundMenu},
                {ErrorCode.NotFoundParentId, LanguageResource.NotFoundParentId},
                {ErrorCode.InvalidFileType, LanguageResource.InvalidFileType},
                {ErrorCode.InvalidFileSize, LanguageResource.InvalidFileSize},
                {ErrorCode.MaximumAllowedSize, LanguageResource.MaximumAllowedSize},
                {ErrorCode.InvalidMobile, LanguageResource.InvalidMobile},
                {ErrorCode.NullAddressEntry, LanguageResource.NullAddressEntry},
                {ErrorCode.NotFoundAddress, LanguageResource.NotFoundAddress},
                {ErrorCode.NullCityEntry, LanguageResource.NullCityEntry},
                {ErrorCode.NotFoundCity, LanguageResource.NotFoundCity},
                {ErrorCode.DuplicateCityName, LanguageResource.DuplicateCityName},
                {ErrorCode.NotFoundCountry, LanguageResource.NotFoundCountry},
                {ErrorCode.NullCountryEntry, LanguageResource.NullCountryEntry},

                {ErrorCode.DuplicateCountryName, LanguageResource.DuplicateCountryName},
                {ErrorCode.NotFoundProvince, LanguageResource.NotFoundProvince},
                {ErrorCode.NullProvinceEntry, LanguageResource.NullProvinceEntry},
                {ErrorCode.DuplicateProvinceName, LanguageResource.DuplicateProvinceName},

                {ErrorCode.NotFoundRegion, LanguageResource.NotFoundRegion},
                {ErrorCode.NullRegionEntry, LanguageResource.NullRegionEntry},
                {ErrorCode.DuplicateRegion, LanguageResource.DuplicateRegion},
                {ErrorCode.DuplicateRegionName, LanguageResource.DuplicateRegionName},

                {ErrorCode.NotFoundContact, LanguageResource.NotFoundContact},
                {ErrorCode.NullContactEntry,  LanguageResource.NullContactEntry},
                {ErrorCode.NullContactEditEntry, LanguageResource.NullContactEditEntry},
                {ErrorCode.DuplicateContact, LanguageResource.DuplicateContact},

                {ErrorCode.NullProfileEntry, LanguageResource.NullProfileEntry},
                {ErrorCode.NotFoundProfile, LanguageResource.NotFoundProfile},
                {ErrorCode.DuplicateProfile, LanguageResource.DuplicateProfile},

                {ErrorCode.NotFoundUserAddress, LanguageResource.NotFoundUserAddress},
                {ErrorCode.NullUserAddressEntry, LanguageResource.NullUserAddressEntry},
                {ErrorCode.DuplicateUserAddress, LanguageResource.DuplicateUserAddress},

                {ErrorCode.NotFoundUserRole, LanguageResource.NotFoundUserRole},
                {ErrorCode.NullUseRoleEntry, LanguageResource.NullUseRoleEntry},
                {ErrorCode.DuplicateUserRole, LanguageResource.DuplicateUserRole},
                {ErrorCode.DuplicateUserName, LanguageResource.DuplicateUserName},
                {ErrorCode.InvalidUser, LanguageResource.InvalidUser},

                {ErrorCode.InvalidFormatMobile, LanguageResource.InvalidFormatMobile},
                {ErrorCode.ExistedMobile, LanguageResource.ExistedMobile},
                {ErrorCode.NotFoundUserGroup, LanguageResource.NotFoundUserGroup},
                {ErrorCode.NotFoundRoleEditEntry, LanguageResource.NotFoundRoleEditEntry},
                {ErrorCode.InvalidEmailFormat, LanguageResource.InvalidEmailFormat},
                {ErrorCode.NullUserEntry, LanguageResource.NullUserEntry},
                {ErrorCode.NullUserEditEntry, LanguageResource.NullUserEditEntry},

                {ErrorCode.InvalidBannerPositionEntry, LanguageResource.InvalidBannerPositionEntry},
                {ErrorCode.InvalidBannerPositionEditEntry, LanguageResource.InvalidBannerPositionEditEntry},
                {ErrorCode.NotFoundBannerType, LanguageResource.NotFoundBannerType},
                {ErrorCode.NotFoundBannerTypeEditEntry, LanguageResource.NotFoundBannerTypeEditEntry},
                {ErrorCode.NotFoundBannerScope, LanguageResource.NotFoundBannerScope},
                {ErrorCode.NotFoundBannerScopeEditEntry, LanguageResource.NotFoundBannerScopeEditEntry},
                {ErrorCode.InvalidBannerScopeId, LanguageResource.InvalidBannerScopeId},
                {ErrorCode.NullReferenceBannerScopeEntry, LanguageResource.NullReferenceBannerScopeEntry},
                {ErrorCode.NotFoundBannerEditEntry, LanguageResource.NotFoundBannerEditEntry},

                {ErrorCode.DuplicateTopicName, LanguageResource.DuplicateTopicName},
                {ErrorCode.NotFoundNewsCategoryEditEntry, LanguageResource.NotFoundNewsCategoryEditEntry},
                {ErrorCode.NotFoundGalleryTopicEntry, LanguageResource.NotFoundGalleryTopicEntry},
                {ErrorCode.NotFoundGalleryTopicEditEntry, LanguageResource.NotFoundGalleryTopicEditEntry},
                {ErrorCode.InvalidTopicName, LanguageResource.InvalidTopicName},
                {ErrorCode.NullGalleryCollectionEntry, LanguageResource.NullGalleryCollectionEntry},
                {ErrorCode.NullCollectionName, LanguageResource.NullCollectionName},
                {ErrorCode.InvalidCollectionName, LanguageResource.InvalidCollectionName},
                {ErrorCode.DuplicateCollectionName, LanguageResource.DuplicateCollectionName},
                {ErrorCode.InvalidCollectionId, LanguageResource.InvalidCollectionId},

                {ErrorCode.NullReferenceGalleryCollectionEditEntry, LanguageResource.NullReferenceGalleryCollectionEditEntry},
                {ErrorCode.NotFoundGalleryCollectionEditEntry, LanguageResource.NotFoundGalleryCollectionEditEntry},
                {ErrorCode.NullGalleryFileEntry, LanguageResource.NullGalleryFileEntry},
                {ErrorCode.NullGalleryFileEditEntry, LanguageResource.NullGalleryFileEditEntry},
                {ErrorCode.NotFoundGalleryFile, LanguageResource.NotFoundGalleryFile},

                {ErrorCode.NullCapabilityEntry, LanguageResource.NullCapabilityEntry},
                {ErrorCode.NotFoundMediaTypeEntry, LanguageResource.NotFoundMediaTypeEntry},

                {ErrorCode.InvalidExtension, LanguageResource.InvalidExtension},
                {ErrorCode.DuplicateTypeName, LanguageResource.DuplicateTypeName},
                {ErrorCode.NotFoundMediaTypeEditEntry, LanguageResource.NotFoundMediaTypeEditEntry},
                {ErrorCode.NotFoundMediaPlayListEntry, LanguageResource.NotFoundMediaPlayListEntry},
                {ErrorCode.NotFoundMediaPlayListEditEntry, LanguageResource.NotFoundMediaPlayListEditEntry},
                {ErrorCode.DuplicatePlayListName, LanguageResource.DuplicatePlayListName},
                {ErrorCode.NotFoundMediaComposerEntry, LanguageResource.NotFoundMediaComposerEntry},
                {ErrorCode.NotFoundMediaComposerEditEntry, LanguageResource.NotFoundMediaComposerEditEntry},
                {ErrorCode.NotFoundMediaComposer, LanguageResource.NotFoundMediaComposer},
                {ErrorCode.NotFoundMediaAlbumEntry, LanguageResource.NotFoundMediaAlbumEntry},
                {ErrorCode.NotFoundMediaAlbumEditEntry, LanguageResource.NotFoundMediaAlbumEditEntry},
                {ErrorCode.NotFoundMediaAlbum, LanguageResource.NotFoundMediaAlbum},
                {ErrorCode.NotFoundMediaArtist, LanguageResource.NotFoundMediaArtist},
                {ErrorCode.NotFoundMediaArtistEntry, LanguageResource.NotFoundMediaArtistEntry},
                {ErrorCode.NotFoundMediaArtistEditEntry, LanguageResource.NotFoundMediaArtistEditEntry},
                {ErrorCode.NotFoundMediaTopic, LanguageResource.NotFoundMediaTopic},
                {ErrorCode.NotFoundMediaTopicEntry, LanguageResource.NotFoundMediaTopicEntry},
                {ErrorCode.NotFoundMediaTopicEditEntry, LanguageResource.NotFoundMediaTopicEditEntry},
                {ErrorCode.NotFoundMediaPlayList, LanguageResource.NotFoundMediaPlayList},

                {ErrorCode.NotFoundCompanyEditEntry, LanguageResource.NotFoundCompanyEditEntry},
                {ErrorCode.NullBanner, LanguageResource.NullBanner},
                {ErrorCode.NullCompany, LanguageResource.NullCompany},
                {ErrorCode.NullGalleryTopic, LanguageResource.NullGalleryTopic},
                {ErrorCode.NotFoundMediaType, LanguageResource.NotFoundMediaType},
                {ErrorCode.DuplicateDocumentFile, LanguageResource.DuplicateDocumentFile},
                {ErrorCode.DuplicateSettingName, LanguageResource.DuplicateSettingName},

                {ErrorCode.NotFoundCustomerEditEntry, LanguageResource.NotFoundCustomerEditEntry},
                {ErrorCode.NullCompanyName, LanguageResource.NullCompanyName},
                {ErrorCode.NullCustomer, LanguageResource.NullCustomer},
                {ErrorCode.DuplicateCurrencyName, LanguageResource.DuplicateCurrencyName},
                {ErrorCode.NullCurrency, LanguageResource.NullCurrency},
                {ErrorCode.NullCurrencyEntry, LanguageResource.NullCurrencyEntry},
                {ErrorCode.NullCurrencyName, LanguageResource.NullCurrencyName},

                {ErrorCode.NullTopicName, LanguageResource.NullTopicName},
                {ErrorCode.NullCurrencyRate, LanguageResource.NullCurrencyRate},
                {ErrorCode.NullCurrencyCode, LanguageResource.NullCurrencyCode},
                {ErrorCode.NullCurrencyRateEntry, LanguageResource.NullCurrencyRateEntry},
                {ErrorCode.DuplicateCurrencyRate, LanguageResource.DuplicateCurrencyRate},
                {ErrorCode.WrongEmailFormat, LanguageResource.WrongEmailFormat},
                {ErrorCode.OverTheAllowedLimit, LanguageResource.OverTheAllowedLimit},
                {ErrorCode.NotFoundVendorEditEntry, LanguageResource.NotFoundVendorEditEntry},
                {ErrorCode.InvalidCountryId, LanguageResource.InvalidCountryId},
                {ErrorCode.InvalidProvinceId, LanguageResource.InvalidProvinceId},
                {ErrorCode.InvalidRegionId, LanguageResource.InvalidRegionId},
                {ErrorCode.UnauthorizedUpload, LanguageResource.UnauthorizedUpload},
                {ErrorCode.DirectoryNotFoundException, LanguageResource.DirectoryNotFoundException},
                {ErrorCode.NullCategoryName, LanguageResource.NullCategoryName},
                {ErrorCode.NotFoundProductCategoryEditEntry, LanguageResource.NotFoundProductCategoryEditEntry},
                {ErrorCode.NullParentNode, LanguageResource.NullParentNode},
                {ErrorCode.EndDateMustBeGreaterThanStartDate, LanguageResource.EndDateMustBeGreaterThanStartDate},
                {ErrorCode.NotFoundProductCommentEntry, LanguageResource.NotFoundProductCommentEntry},
                {ErrorCode.NotFoundProductComment, LanguageResource.NotFoundProductComment},
                {ErrorCode.NullCommentName, LanguageResource.NullCommentName},
                {ErrorCode.NullCommentEmail, LanguageResource.NullCommentEmail},
                {ErrorCode.NullApplicationLanguageEntry, LanguageResource.NullApplicationLanguageEntry},

                {ErrorCode.DuplicateLanguageCode, LanguageResource.DuplicateLanguageCode},
                {ErrorCode.NullCustomerNo, LanguageResource.NullCustomerNo},
                {ErrorCode.DuplicateCustomerNo, LanguageResource.DuplicateCustomerNo},
                {ErrorCode.InvalidProductCode, LanguageResource.InvalidProductCode},
                {ErrorCode.DuplicatedProductCode, LanguageResource.DuplicatedProductCode},
                {ErrorCode.DuplicatedProductName, LanguageResource.DuplicatedProductName},
                {ErrorCode.NullModuleName, LanguageResource.NullModuleName},
                {ErrorCode.NullTypeName, LanguageResource.NullTypeName},
                {ErrorCode.NullTypeExtension, LanguageResource.NullTypeExtension},
                {ErrorCode.NullExtension, LanguageResource.NullExtension},
                {ErrorCode.NullTypePath, LanguageResource.NullTypePath},
                {ErrorCode.InvalidTypePath, LanguageResource.InvalidTypePath},
                {ErrorCode.NullPlayListName, LanguageResource.NullPlayListName},
                {ErrorCode.InvalidAlbumId, LanguageResource.InvalidAlbumId},
                {ErrorCode.InvalidFileId, LanguageResource.InvalidFileId},
                {ErrorCode.NotFoundMediaFile, LanguageResource.NotFoundMediaFile},
                {ErrorCode.NullMediaFileEntry, LanguageResource.NullMediaFileEntry},
                {ErrorCode.InvalidTypeId, LanguageResource.InvalidTypeId},
                {ErrorCode.DuplicateFolderName, LanguageResource.DuplicateFolderName},
                {ErrorCode.NullMediaFileEditEntry, LanguageResource.NullMediaFileEditEntry},
                {ErrorCode.InvalidTopicId, LanguageResource.InvalidTopicId},
                {ErrorCode.InvalidMediaId, LanguageResource.InvalidMediaId},

                {ErrorCode.NullShippingMethodEntry, LanguageResource.NullShippingMethodEntry},
                {ErrorCode.NullShippingMethodEditEntry, LanguageResource.NullShippingMethodEditEntry},
                {ErrorCode.NotFoundShippingMethod, LanguageResource.NotFoundShippingMethod},
                {ErrorCode.NullShippingMethodName, LanguageResource.NullShippingMethodName},
                {ErrorCode.InvalidShippingMethodName, LanguageResource.InvalidShippingMethodName},
                {ErrorCode.DuplicateShippingMethodName, LanguageResource.DuplicateShippingMethodName},
                {ErrorCode.NullShippingCarrierEntry, LanguageResource.NullShippingCarrierEntry},
                {ErrorCode.NullShippingCarrierEditEntry, LanguageResource.NullShippingCarrierEditEntry},
                {ErrorCode.NotFoundShippingCarrier, LanguageResource.NotFoundShippingCarrier},
                {ErrorCode.NullShippingCarrierName, LanguageResource.NullShippingCarrierName},
                {ErrorCode.InvalidShippingCarrierName, LanguageResource.InvalidShippingCarrierName},
                {ErrorCode.DuplicateShippingCarrierName, LanguageResource.DuplicateShippingCarrierName},
                {ErrorCode.NullShippingRateEntry, LanguageResource.NullShippingRateEntry},
                {ErrorCode.NullShippingRateEditEntry, LanguageResource.NullShippingRateEditEntry},
                {ErrorCode.NotFoundShippingRate, LanguageResource.NotFoundShippingRate},
                {ErrorCode.NullShippingRateName, LanguageResource.NullShippingRateName},
                {ErrorCode.InvalidShippingRateName, LanguageResource.InvalidShippingRateName},
                {ErrorCode.DuplicateShippingRateName, LanguageResource.DuplicateShippingRateName},

                {ErrorCode.NullServicePackEntry, LanguageResource.NullServicePackEntry},
                {ErrorCode.NullServicePackName, LanguageResource.NullServicePackName},
                {ErrorCode.InvalidServicePackName, LanguageResource.InvalidServicePackName},
                {ErrorCode.InvalidServicePackId, LanguageResource.InvalidServicePackId},
                {ErrorCode.DuplicateServicePackName, LanguageResource.DuplicateServicePackName},
                {ErrorCode.NullServicePackEditEntry, LanguageResource.NullServicePackEditEntry},
                {ErrorCode.NotFoundServicePack, LanguageResource.NotFoundServicePack},
                {ErrorCode.InvalidEmployeeId, LanguageResource.InvalidEmployeeId},
                {ErrorCode.InvalidCustomerId, LanguageResource.InvalidCustomerId},

                {ErrorCode.NullServiceBookingEntry, LanguageResource.NullServiceBookingEntry},
                {ErrorCode.NullServiceBookingEditEntry, LanguageResource.NullServiceBookingEditEntry},
                {ErrorCode.DuplicateServiceBooking, LanguageResource.DuplicateServiceBooking},
                {ErrorCode.NotFoundServiceBooking, LanguageResource.NotFoundServiceBooking},
                {ErrorCode.NullServiceDiscountEntry, LanguageResource.NullServiceDiscountEntry},
                {ErrorCode.NullServiceDiscountEditEntry, LanguageResource.NullServiceDiscountEditEntry},
                {ErrorCode.NotFoundServiceDiscount, LanguageResource.NotFoundServiceDiscount},
                {ErrorCode.DuplicateServiceDiscount, LanguageResource.DuplicateServiceDiscount},

                {ErrorCode.NullProductDiscountEditEntry, LanguageResource.NullProductDiscountEditEntry},
                {ErrorCode.NullEmployeeEntry, LanguageResource.NullEmployeeEntry},
                {ErrorCode.NotFoundEmployee, LanguageResource.NotFoundEmployee},
                {ErrorCode.NullEmployeeName, LanguageResource.NullEmployeeName},
                {ErrorCode.InvalidEmployeeName, LanguageResource.InvalidEmployeeName},
                {ErrorCode.DuplicateEmployee, LanguageResource.DuplicateEmployee},

                {ErrorCode.NullJobPositionEntry, LanguageResource.NullJobPositionEntry},
                {ErrorCode.NullPositionName, LanguageResource.NullPositionName},
                {ErrorCode.InvalidPositionName, LanguageResource.InvalidPositionName},
                {ErrorCode.DuplicatePositionName, LanguageResource.DuplicatePositionName},
                {ErrorCode.NullJobPositionEditEntry, LanguageResource.NullJobPositionEditEntry},
                {ErrorCode.NotFoundJobPosition, LanguageResource.NotFoundJobPosition},
                {ErrorCode.NullEmployeeNo, LanguageResource.NullEmployeeNo},
                {ErrorCode.InvalidEmployeeNo, LanguageResource.InvalidEmployeeNo},
                {ErrorCode.DuplicateEmployeeNo, LanguageResource.DuplicateEmployeeNo},
                {ErrorCode.NullEmployeeEditEntry, LanguageResource.NullEmployeeEditEntry},
                {ErrorCode.NullEmployee, LanguageResource.NullEmployee},
                {ErrorCode.NullContract, LanguageResource.NullContract},
                {ErrorCode.InvalidContractId, LanguageResource.InvalidContractId},
                {ErrorCode.InvalidContractTypeId, LanguageResource.InvalidContractTypeId},
                {ErrorCode.NullCustomerName, LanguageResource.NullCustomerName},
                {ErrorCode.NullOrderNo, LanguageResource.NullOrderNo},
                {ErrorCode.NullProductNo, LanguageResource.NullProductNo},
                {ErrorCode.NullProductCode, LanguageResource.NullProductCode},
                {ErrorCode.NullProductCategoryId, LanguageResource.NullProductCategoryId},
                {ErrorCode.NullProductTypeId, LanguageResource.NullProductTypeId},
                {ErrorCode.NullVendorId, LanguageResource.NullVendorId},
                {ErrorCode.NotFoundContractEntry, LanguageResource.NotFoundContractEntry},
                {ErrorCode.NullContractNo, LanguageResource.NullContractNo},
                {ErrorCode.InvalidContractNo, LanguageResource.InvalidContractNo},
                {ErrorCode.DuplicateContractNo, LanguageResource.DuplicateContractNo},
                {ErrorCode.NotFoundContractEditEntry, LanguageResource.NotFoundContractEditEntry},

                {ErrorCode.NullServicePackDurationEntry, LanguageResource.NullServicePackDurationEntry},
                {ErrorCode.NullDurationName, LanguageResource.NullDurationName},
                {ErrorCode.InvalidDurationName, LanguageResource.InvalidDurationName},
                {ErrorCode.DuplicateDurationName, LanguageResource.DuplicateDurationName},
                {ErrorCode.DuplicateAllotedTime, LanguageResource.DuplicateAllotedTime},
                {ErrorCode.NullServicePackDurationEditEntry, LanguageResource.NullServicePackDurationEditEntry},
                {ErrorCode.NotFoundServicePackDuration, LanguageResource.NotFoundServicePackDuration},
                {ErrorCode.PleaseSelectEmployee, LanguageResource.PleaseSelectEmployee},
                {ErrorCode.PleaseSelectEmployeeProvider, LanguageResource.PleaseSelectEmployeeProvider},
                {ErrorCode.NullProvider, LanguageResource.NotFoundContractEditEntry},

                {ErrorCode.NullMailServerProviderEntry, LanguageResource.NullMailServerProviderEntry},
                {ErrorCode.NullMailServerProviderName, LanguageResource.NullMailServerProviderName},
                {ErrorCode.InvalidMailServerProviderName, LanguageResource.InvalidMailServerProviderName},
                {ErrorCode.DuplicateMailServerProviderName, LanguageResource.DuplicateMailServerProviderName},
                {ErrorCode.NullMailServerProtocol, LanguageResource.NullMailServerProtocol},
                {ErrorCode.InvalidMailServerProtocol, LanguageResource.InvalidMailServerProtocol},
                {ErrorCode.NullIncomingMailServerHost, LanguageResource.NullIncomingMailServerHost},
                {ErrorCode.InvalidIncomingMailServerHost, LanguageResource.InvalidIncomingMailServerHost},
                {ErrorCode.NullIncomingMailServerPort, LanguageResource.NullIncomingMailServerPort},
                {ErrorCode.InvalidIncomingMailServerPort, LanguageResource.InvalidIncomingMailServerPort},
                {ErrorCode.NullMailServerProviderEditEntry, LanguageResource.NullMailServerProviderEditEntry},
                {ErrorCode.NotFoundMailServerProviderEditEntry, LanguageResource.NotFoundMailServerProviderEditEntry},
                {ErrorCode.NotFoundMailServerProvider, LanguageResource.NotFoundMailServerProvider},
                {ErrorCode.InvalidMailServerProviderId, LanguageResource.InvalidMailServerProviderId},
                {ErrorCode.NotFoundMailServerProviderId, LanguageResource.NotFoundMailServerProviderId},
                {ErrorCode.NullMessageTypeName, LanguageResource.NullMessageTypeName},
                {ErrorCode.InvalidMessageTypeName, LanguageResource.InvalidMessageTypeName},
                {ErrorCode.DuplicateMessageTypeName, LanguageResource.DuplicateMessageTypeName},
                {ErrorCode.NotFoundMessageType, LanguageResource.NotFoundMessageType},
                {ErrorCode.NotFoundMessageTypeId, LanguageResource.NotFoundMessageTypeId},
                {ErrorCode.NullTemplateName, LanguageResource.NullTemplateName},
                {ErrorCode.DuplicateTemplateName, LanguageResource.DuplicateTemplateName},
                {ErrorCode.NotFoundMessageTemplate, LanguageResource.NotFoundMessageTemplate},
                {ErrorCode.NullTemplateId, LanguageResource.NullTemplateId},
                {ErrorCode.NotFoundTemplateId, LanguageResource.NotFoundTemplateId},
                {ErrorCode.NullMessageTemplateEntry, LanguageResource.NullMessageTemplateEntry},
                {ErrorCode.NullMessageTemplateEditEntry, LanguageResource.NullMessageTemplateEditEntry},
                {ErrorCode.NullTemplateBody, LanguageResource.NullTemplateBody},
                {ErrorCode.NotFoundMessageCategory, LanguageResource.NotFoundMessageCategory},

                {ErrorCode.NullMailAccountEntry, LanguageResource.NullMailAccountEntry},
                {ErrorCode.NullSenderName, LanguageResource.NullSenderName},
                {ErrorCode.InvalidSenderName, LanguageResource.InvalidSenderName},
                {ErrorCode.NullMailAddress, LanguageResource.NullMailAddress},
                {ErrorCode.InvalidMailAddress, LanguageResource.InvalidMailAddress},
                {ErrorCode.NullPassword, LanguageResource.NullPassword},
                {ErrorCode.DuplicateSenderName, LanguageResource.DuplicateSenderName},
                {ErrorCode.DuplicateMailAddress, LanguageResource.DuplicateMailAddress},
                {ErrorCode.NullMailAccountEditEntry, LanguageResource.NullMailAccountEditEntry},
                {ErrorCode.NotFoundMailAccount, LanguageResource.NotFoundMailAccount},
                {ErrorCode.NotFoundMailAccountId, LanguageResource.NotFoundMailAccountId},
                {ErrorCode.NullMessageCategory, LanguageResource.NullMessageCategory},
                {ErrorCode.NullCategoryId, LanguageResource.NullCategoryId},
                {ErrorCode.NullMessageTypeId, LanguageResource.NullMessageTypeId},
                {ErrorCode.InvalidMessageTypeId, LanguageResource.InvalidMessageTypeId},
                {ErrorCode.NotFoundTypeId, LanguageResource.NotFoundTypeId},
                {ErrorCode.NullPackageName, LanguageResource.NullPackageName},
                {ErrorCode.InvalidPackageName, LanguageResource.InvalidPackageName},
                {ErrorCode.DuplicatePackageName, LanguageResource.DuplicatePackageName},
                {ErrorCode.InvalidPackageId, LanguageResource.InvalidPackageId},
                {ErrorCode.NotFoundPackageId, LanguageResource.NotFoundPackageId},
                {ErrorCode.NullTemplateKey, LanguageResource.NullTemplateKey},
                {ErrorCode.NullTemplateSrc, LanguageResource.NullTemplateSrc},
                {ErrorCode.NotFoundBackgroundId, LanguageResource.NotFoundBackgroundId},
                {ErrorCode.NullBackgroundName, LanguageResource.NullBackgroundName},
                {ErrorCode.InvalidBackgroundName, LanguageResource.InvalidBackgroundName},
                {ErrorCode.DuplicateBackgroundName, LanguageResource.DuplicateBackgroundName},

                {ErrorCode.PleaseBrowseFile, LanguageResource.PleaseBrowseFile},
                {ErrorCode.PleaseBrowseFileOrInputLink, LanguageResource.PleaseBrowseFileOrInputLink},
                {ErrorCode.NotFoundSkin, LanguageResource.NotFoundSkin},
                {ErrorCode.NotFoundSkinPackage, LanguageResource.NotFoundSkinPackage},
                {ErrorCode.NotFoundSkinPackageEntry, LanguageResource.NotFoundSkinPackageEntry},
                {ErrorCode.InvaliEventMessage, LanguageResource.InvaliEventMessage},
                {ErrorCode.NotFoundEventEntry, LanguageResource.NotFoundEventEntry},
                {ErrorCode.NotFoundEventTypeEntry, LanguageResource.NotFoundEventTypeEntry},
                {ErrorCode.NullEventTypeEditEntry, LanguageResource.NullEventTypeEditEntry},
                {ErrorCode.NotFoundEventId, LanguageResource.NotFoundEventId},
                {ErrorCode.NullEventEditEntry, LanguageResource.NullEventEditEntry},
                {ErrorCode.NullEventCode, LanguageResource.NullEventCode},
                {ErrorCode.InvalidEventCode, LanguageResource.InvalidEventCode},
                {ErrorCode.DuplicateEventCode, LanguageResource.DuplicateEventCode},
                {ErrorCode.InvalidEventTypeId, LanguageResource.InvalidEventTypeId},
                {ErrorCode.InvalidEventId, LanguageResource.InvalidEventId},

                {ErrorCode.NotFoundNotificationType, LanguageResource.NotFoundNotificationType },
                {ErrorCode.NullNotificationTypeName, LanguageResource.NullNotificationTypeName },
                {ErrorCode.InvalidNotificationTargetTypeId, LanguageResource.InvalidNotificationTargetTypeId },
                {ErrorCode.DuplicateNotificationTypeName, LanguageResource.DuplicateNotificationTypeName },

                {ErrorCode.NotFoundNotificationSender, LanguageResource.NotFoundNotificationSender },
                {ErrorCode.NotFoundNotificationSenderId,LanguageResource.NotFoundNotificationSenderId },
                {ErrorCode.NotFoundNotificationTarget, LanguageResource.NotFoundNotificationTarget },
                {ErrorCode.NullMessageQueueEditEntry, LanguageResource.NullMessageQueueEditEntry },
                {ErrorCode.NotFoundNotificationTypeId, LanguageResource.NotFoundNotificationTypeId },
                {ErrorCode.NullTargetName, LanguageResource.NullTargetName },
                {ErrorCode.InvalidTargetName, LanguageResource.InvalidTargetName },
                {ErrorCode.DuplicateTargetName, LanguageResource.DuplicateTargetName },
                {ErrorCode.NotFoundNotificationTargetDefault, LanguageResource.NotFoundNotificationTargetDefault },
                {ErrorCode.NotFoundNotificationTargetDefaultId, LanguageResource.NotFoundNotificationTargetDefaultId },

                {ErrorCode.UnApproved, LanguageResource.UnApproved },
                {ErrorCode.IsLockedOut, LanguageResource.IsLockedOut },
                {ErrorCode.NotFoundUserName, LanguageResource.NotFoundUserName },

                {ErrorCode.NullServiceCategoryEntry, LanguageResource.NullServiceCategoryEntry },
                {ErrorCode.NullServiceCategoryEditEntry, LanguageResource.NullServiceCategoryEditEntry },
                {ErrorCode.NotFoundServiceCategoryEntry, LanguageResource.NotFoundServiceCategoryEntry },
                {ErrorCode.NotFoundServiceCategoryEditEntry, LanguageResource.NotFoundServiceCategoryEditEntry },

                {ErrorCode.InVerified, LanguageResource.InVerified },
                {ErrorCode.InvalidBirthday, LanguageResource.InvalidBirthday },
                {ErrorCode.BirthdayMustBeGreaterThanMinDate,  LanguageResource.BirthdayMustBeGreaterThanMinDate },

                {ErrorCode.ExistedHomePhone,  LanguageResource.ExistedHomePhone },
                {ErrorCode.ExistedWorkPhone,  LanguageResource.ExistedWorkPhone },
                {ErrorCode.NullCustomerRegisterEntry,  LanguageResource.NullCustomerRegisterEntry },
                {ErrorCode.NullFeedbackEntry, LanguageResource.NullFeedbackEntry },
                {ErrorCode.NullSubject, LanguageResource.NullSubject },
                {ErrorCode.NullBody,  LanguageResource.NullBody },

                {ErrorCode.NotFoundFeedback, LanguageResource.NotFoundFeedback },
                {ErrorCode.NotFoundIdentity, LanguageResource.NotFoundIdentity },
                {ErrorCode.NotFoundKey, LanguageResource.NotFoundKey },
                {ErrorCode.PasswordMismatch, LanguageResource.PasswordMismatch },
                {ErrorCode.NullPageCode, LanguageResource.NullPageCode },
                {ErrorCode.InvalidPageCode, LanguageResource.InvalidPageCode },
                {ErrorCode.DuplicatePageCode, LanguageResource.DuplicatePageCode },
                {ErrorCode.NullModuleCode, LanguageResource.NullModuleCode },
                {ErrorCode.InvalidModuleCode, LanguageResource.InvalidModuleCode },
                {ErrorCode.DuplicateModuleCode, LanguageResource.DuplicateModuleCode },
                {ErrorCode.NullModuleCapabilityCode, LanguageResource.NullModuleCapabilityCode },
                {ErrorCode.InvalidModuleCapabilityCode, LanguageResource.InvalidModuleCapabilityCode },
                {ErrorCode.DuplicateModuleCapabilityCode, LanguageResource.DuplicateModuleCapabilityCode },
                {ErrorCode.InvalidModuleName, LanguageResource.InvalidModuleName },
                {ErrorCode.InvalidModuleTitle, LanguageResource.InvalidModuleTitle },
                {ErrorCode.NullCapabilityName, LanguageResource.NullCapabilityName },
                {ErrorCode.InvalidCapabilityName, LanguageResource.InvalidCapabilityName },
                {ErrorCode.DuplicateCapabilityName, LanguageResource.DuplicateCapabilityName },
                {ErrorCode.NullCapabilityCode, LanguageResource.NullCapabilityCode },
                {ErrorCode.InvalidCapabilityCode,LanguageResource.InvalidCapabilityCode },
                {ErrorCode.DuplicateCapabilityCode, LanguageResource.DuplicateCapabilityCode },

                {ErrorCode.NotFoundSkill, LanguageResource.NotFoundSkill },
                {ErrorCode.NullSkillName, LanguageResource.NullSkillName },
                {ErrorCode.InvalidSkillName, LanguageResource.InvalidSkillName },
                {ErrorCode.DuplicateSkillName, LanguageResource.DuplicateSkillName },
                {ErrorCode.NotFoundPosition, LanguageResource.NotFoundPosition },

                {ErrorCode.NullEmployeeAvailabilityEntry, LanguageResource.NullEmployeeAvailabilityEntry },
                {ErrorCode.NullTimeZoneId, LanguageResource.NullTimeZoneId },
                {ErrorCode.NullEmployeeAvailability, LanguageResource.NullEmployeeAvailability },
                {ErrorCode.NullEmployeeTimeOffEntry, LanguageResource.NullEmployeeTimeOffEntry },
                {ErrorCode.NullTimeOffType, LanguageResource.NullTimeOffType },
                {ErrorCode.NullEmployeeTimeOff, LanguageResource.NullEmployeeTimeOff },
                {ErrorCode.NullReason, LanguageResource.NullReason },
                {ErrorCode.NotFoundJobPositionSkill, LanguageResource.NotFoundJobPositionSkill },
                {ErrorCode.NullQualificationEntry, LanguageResource.NullQualificationEntry },
                {ErrorCode.NullQualificationNo, LanguageResource.NullQualificationNo },
                {ErrorCode.InvalidQualificationNo, LanguageResource.InvalidQualificationNo },
                {ErrorCode.DuplicateQualificationNo, LanguageResource.DuplicateQualificationNo },
                {ErrorCode.NullQualificationEditEntry, LanguageResource.NullQualificationEditEntry },
                {ErrorCode.NotFoundQualification, LanguageResource.NotFoundQualification },
                {ErrorCode.InvalidCompany, LanguageResource.InvalidCompany },
                {ErrorCode.InvalidQualificationId,  LanguageResource.InvalidQualificationId },
                {ErrorCode.NullRewardDisciplineEntry,  LanguageResource.NullRewardDisciplineEntry },
                {ErrorCode.NotFoundRewardDiscipline,  LanguageResource.NotFoundRewardDiscipline },
                {ErrorCode.NotFoundSalary,  LanguageResource.NotFoundSalary },
                {ErrorCode.NullSalaryEntry,  LanguageResource.NullSalaryEntry },
                {ErrorCode.NullSalaryEditEntry,  LanguageResource.NullSalaryEditEntry },
                {ErrorCode.NullSalary,  LanguageResource.NullSalary },
                {ErrorCode.NotFoundSalaryId,  LanguageResource.NotFoundSalaryId },
                {ErrorCode.InvalidSalaryId, LanguageResource.InvalidSalaryId },
                {ErrorCode.NullSkillEntry, LanguageResource.NullSkillEntry },
                {ErrorCode.NullSkillEditEntry,LanguageResource.NullSkillEditEntry },
                {ErrorCode.NullSkill, LanguageResource.NullSkill },
                {ErrorCode.InvalidSkillId, LanguageResource.InvalidSkillId },
                {ErrorCode.NullTerminationEntry, LanguageResource.NullTerminationEntry },
                {ErrorCode.InvalidReason, LanguageResource.InvalidReason },
                {ErrorCode.NullTerminationEditEntry, LanguageResource.NullTerminationEditEntry },
                {ErrorCode.InvalidTerminationId, LanguageResource.InvalidTerminationId },
                {ErrorCode.NullWorkingHistory, LanguageResource.NullWorkingHistory },
                {ErrorCode.NullWorkingHistoryEditEntry, LanguageResource.NullWorkingHistoryEditEntry },
                {ErrorCode.InvalidWorkingHistoryId, LanguageResource.InvalidWorkingHistoryId },
                {ErrorCode.NullPublicHolidaySetEntry, LanguageResource.NullPublicHolidaySetEntry },
                {ErrorCode.InvalidPublicHolidaySetName, LanguageResource.InvalidPublicHolidaySetName },
                {ErrorCode.InvalidPublicHolidaySetId, LanguageResource.InvalidPublicHolidaySetId },
                {ErrorCode.NullPublicHolidaySetEditEntry, LanguageResource.NullPublicHolidaySetEditEntry },
                {ErrorCode.DuplicatePublicHolidaySet, LanguageResource.DuplicatePublicHolidaySet },
                {ErrorCode.NullDescription, LanguageResource.NullDescription },
                {ErrorCode.NullPublicHolidayEntry, LanguageResource.NullPublicHolidayEntry },
                {ErrorCode.DuplicatePublicHoliday, LanguageResource.DuplicatePublicHoliday },
                {ErrorCode.NullPublicHolidayEditEntry, LanguageResource.NullPublicHolidayEditEntry },
                {ErrorCode.InvalidTopicCode,  LanguageResource.InvalidTopicCode },
                {ErrorCode.DuplicateTopicCode, LanguageResource.DuplicateTopicCode },

                {ErrorCode.NullNewsId, LanguageResource.NullNewsId },
                {ErrorCode.NotFoundNewsId, LanguageResource.NotFoundNewsId },
                {ErrorCode.InvalidNewsId, LanguageResource.InvalidNewsId },
                {ErrorCode.NullCommentText, LanguageResource.NullCommentText },
                {ErrorCode.InvalidRate, LanguageResource.InvalidRate },
                {ErrorCode.NullProductId, LanguageResource.NullProductId },
                {ErrorCode.NotFoundProductId, LanguageResource.NotFoundProductId },
                {ErrorCode.NullServicePackId, LanguageResource.NullServicePackId },
                {ErrorCode.NullTypeId, LanguageResource.NullTypeId },
                {ErrorCode.NullTopicId, LanguageResource.NullTopicId },
                {ErrorCode.NullFolder, LanguageResource.NullFolder },
                {ErrorCode.NullFileSource, LanguageResource.NullFileSource },

                {ErrorCode.InvalidServicePackType, LanguageResource.InvalidServicePackType },
                {ErrorCode.NullServiceBookingOrderEntry, LanguageResource.NullServiceBookingOrderEntry },
                {ErrorCode.InvalidBookingId, LanguageResource.InvalidBookingId },
                {ErrorCode.DuplicateServiceBookingOrder,LanguageResource.DuplicateServiceBookingOrder },
                {ErrorCode.DuplicatePartnerName, LanguageResource.DuplicatePartnerName },
                {ErrorCode.NullPartnerName,LanguageResource.NullPartnerName },
                {ErrorCode.NotFoundVendorPartnerEditEntry,LanguageResource.NotFoundVendorPartnerEditEntry },
                {ErrorCode.NotFoundVendorPartner, LanguageResource.NotFoundVendorPartner },
                {ErrorCode.NotFoundPartner, LanguageResource.NotFoundPartner },
                {ErrorCode.NotFoundSiteMapEntry, LanguageResource.NotFoundSiteMapEntry },
                {ErrorCode.NullAction,LanguageResource.NullAction },
                {ErrorCode.InvalidAction, LanguageResource.InvalidAction },
                {ErrorCode.NullController, LanguageResource.NullController },
                {ErrorCode.InvalidController, LanguageResource.InvalidController },
                {ErrorCode.DuplicateControllerAction, LanguageResource.DuplicateControllerAction },
                {ErrorCode.NotFoundSiteMapEditEntry, LanguageResource.NotFoundSiteMapEditEntry },
                {ErrorCode.NotFoundSiteMap, LanguageResource.NotFoundSiteMap },
                {ErrorCode.NullCountry, LanguageResource.NullCountry },
                {ErrorCode.NullStreet,LanguageResource.NullStreet },
                {ErrorCode.NullName, LanguageResource.NullName },

                {ErrorCode.NullServicePeriodEntry, LanguageResource.NullServicePeriodEntry },
                {ErrorCode.NullServicePeriodEditEntry, LanguageResource.NullServicePeriodEditEntry },
                {ErrorCode.NotFoundServicePeriod, LanguageResource.NotFoundServicePeriod },
                {ErrorCode.InvalidPeriodId, LanguageResource.InvalidPeriodId },
                {ErrorCode.InvalidPeriodName, LanguageResource.InvalidPeriodName },
                {ErrorCode.NullPeriodName, LanguageResource.NullPeriodName },
                {ErrorCode.DuplicatePeriodName, LanguageResource.DuplicatePeriodName },
                {ErrorCode.DuplicateOptionName, LanguageResource.DuplicateOptionName },
                {ErrorCode.NotFoundPackageOption, LanguageResource.NotFoundPackageOption },
                {ErrorCode.NullPackageOption, LanguageResource.NullPackageOption },

                {ErrorCode.NullServiceTaxRateEntry, LanguageResource.NullServiceTaxRateEntry },
                {ErrorCode.NullServiceTaxRate, LanguageResource.NullServiceTaxRate },
                {ErrorCode.NullServiceTaxRateEditEntry, LanguageResource.NullServiceTaxRateEditEntry },
                {ErrorCode.NotFoundServiceTaxRate, LanguageResource.NotFoundServiceTaxRate },
                {ErrorCode.InvalidTaxRate, LanguageResource.InvalidTaxRate },
                {ErrorCode.InvalidTaxRateId, LanguageResource.InvalidTaxRateId },
                {ErrorCode.NullProductTaxRateEditEntry, LanguageResource.NullProductTaxRateEditEntry },

                {ErrorCode.NullOrderShipmentEntry, LanguageResource.NullOrderShipmentEntry },
                {ErrorCode.NotFoundOrderShipmentEntry, LanguageResource.NotFoundOrderShipmentEntry },
                {ErrorCode.NullReceiverAddress, LanguageResource.NullReceiverAddress },
                {ErrorCode.InvalidPromotionType, LanguageResource.InvalidPromotionType },
                {ErrorCode.DuplicatePromotionCode, LanguageResource.DuplicatePromotionCode },
                {ErrorCode.InvalidServiceBookingOrderEntry, LanguageResource.InvalidServiceBookingOrderEntry },
                {ErrorCode.NotFoundHashedPassword, LanguageResource.NotFoundHashedPassword },
                {ErrorCode.NotFoundPassword, LanguageResource.NotFoundPassword },
                {ErrorCode.NotFoundRoleId, LanguageResource.NotFoundRoleId },
                {ErrorCode.NotFoundVendorId, LanguageResource.NotFoundVendorId },
                {ErrorCode.NotFoundApplicationId, LanguageResource.NotFoundApplicationId },
                {ErrorCode.NotFoundLanguageCode, LanguageResource.NotFoundLanguageCode },

                {ErrorCode.NullServicePackTypeEntry, LanguageResource.NullServicePackTypeEntry },
                {ErrorCode.NullServicePackTypeEditEntry, LanguageResource.NullServicePackTypeEditEntry },
                {ErrorCode.NotFoundServicePackType, LanguageResource.NotFoundServicePackType },
                {ErrorCode.NullServiceBookingOrderDetailTempEditEntry, LanguageResource.NullServiceBookingOrderDetailTempEditEntry },
                {ErrorCode.NotFoundServiceBookingDetail, LanguageResource.NotFoundServiceBookingDetail },
                {ErrorCode.NotFoundServiceBookingDetailTemp, LanguageResource.NotFoundServiceBookingDetailTemp },
                {ErrorCode.NullPostedPackages, LanguageResource.NullPostedPackages },
                {ErrorCode.DependentProductsBasedOnCategory, LanguageResource.DependentProductsBasedOnCategory },
                {ErrorCode.NotFoundOrderProductTempEntry, LanguageResource.NotFoundOrderProductTempEntry },
                {ErrorCode.NotFoundOrderShipment, LanguageResource.NotFoundOrderShipment },
                {ErrorCode.NotFoundShipment, LanguageResource.NotFoundOrderShipment },
                {ErrorCode.NotFoundPaypalSetting, LanguageResource.NotFoundPaypalSetting },
                {ErrorCode.NotFoundCustomerPayment, LanguageResource.NotFoundCustomerPayment },
                {ErrorCode.InvalidShippingMethodId, LanguageResource.InvalidShippingMethodId },
                {ErrorCode.CannotSaveOrderTemp,LanguageResource.CannotSaveOrderTemp },
                {ErrorCode.CannotSaveOrderProductTemp, LanguageResource.CannotSaveOrderProductTemp },
                {ErrorCode.SessionTimeOut, LanguageResource.SessionTimeOut },
                {ErrorCode.EmptyCart, LanguageResource.EmptyCart },
                {ErrorCode.NullOrderTransactionEntry, LanguageResource.NullOrderTransactionEntry },
                {ErrorCode.QuantityNotSufficient, LanguageResource.OrderQuantityNotSufficient },
                {ErrorCode.PromotionCodeUtilized, LanguageResource.OrderPromoCodeUtilized },
                {ErrorCode.CannotSaveOrder,LanguageResource.CannotSaveOrder },
                {ErrorCode.NotFoundPostalCode, LanguageResource.NotFoundPostalCode },
                {ErrorCode.SessionTimeout, LanguageResource.SessionTimeOut },
                {ErrorCode.Timeout, LanguageResource.Timeout},
                {ErrorCode.UnableToGetVideoThumbnail, LanguageResource.UnableToGetVideoThumbnail},
                {ErrorCode.InvalidVideoPath, LanguageResource.InvalidVideoPath},
                {ErrorCode.NullReferenceForFileUpload, LanguageResource.NullReferenceForFileUpload},
                {ErrorCode.NotFoundDocumentation, LanguageResource.NotFoundDocumentation},
                {ErrorCode.NullReferenceIdentity, LanguageResource.NullReferenceIdentity},
                {ErrorCode.NullApplicationSetting, LanguageResource.NullApplicationSetting},
                {ErrorCode.NotFoundCategory, LanguageResource.NotFoundCategory},
                {ErrorCode.NullCategory, LanguageResource.NullCategory},
                {ErrorCode.InvalidAccount, LanguageResource.InvalidAccount},
                {ErrorCode.UsernameOrPasswordMismatch, LanguageResource.UsernameOrPasswordMismatch},
                {ErrorCode.PaypalFailure, LanguageResource.PaypalFailure},
                {ErrorCode.PaypalTransactionFailure, LanguageResource.PaypalTransactionFailure},
                {ErrorCode.PaymentFailure, LanguageResource.PaymentFailure},
                {ErrorCode.UnableToAccessToken, LanguageResource.UnableToAccessToken},
                {ErrorCode.NotFoundOrderProductEditEntry, LanguageResource.NotFoundOrderProductEditEntry},
                {ErrorCode.NotFoundOrderProductTempEditEntry, LanguageResource.NotFoundOrderProductTempEditEntry},
                {ErrorCode.NotFoundBrand, LanguageResource.NotFoundBrand},

                {ErrorCode.NotFoundPayGate, LanguageResource.NotFoundPayGate},
                {ErrorCode.NotFoundPayGateSetting, LanguageResource.NotFoundPayGateSetting},

              
            };

        }

        public static string GetValue(ErrorCode key)
        {
            return Messages[key];
        }
    }
}
