CREATE TABLE [dbo].[Container] (
    [ContainerId]          INT              NOT NULL,
    [ContentItemId]        INT              NOT NULL,
    [ApplicationId]        INT              NULL,
    [ContainerOrder]       INT              NOT NULL,
    [ContainerName]        NVARCHAR (50)    NOT NULL,
    [ParentId]             INT              NULL,
    [Level]                INT              NULL,
    [Lineage]              VARCHAR (250)    NULL,
    [DisableLink]          BIT              NULL,
    [Title]                NVARCHAR (200)   NULL,
    [DisplayTitle]         BIT              NOT NULL,
    [IsDashBoard]          BIT              NULL,
    [Description]          NVARCHAR (500)   NULL,
    [Keywords]             NVARCHAR (500)   NULL,
    [Url]                  NVARCHAR (255)   NULL,
    [ContainerPath]        NVARCHAR (255)   NULL,
    [StartDate]            DATETIME         NULL,
    [EndDate]              DATETIME         NULL,
    [PageHeadText]         NVARCHAR (500)   NULL,
    [PageFooterText]       NVARCHAR (MAX)   NULL,
    [PageControlBar]       NVARCHAR (MAX)   NULL,
    [IsDeleted]            BIT              NOT NULL,
    [IsSecure]             BIT              NOT NULL,
    [IsVisible]            BIT              NOT NULL,
    [PermanentRedirect]    BIT              NOT NULL,
    [SiteMapPriority]      FLOAT (53)       NOT NULL,
    [CssClass]             NVARCHAR (100)   NULL,
    [IconFile]             NVARCHAR (100)   NULL,
    [IconFileLarge]        NVARCHAR (100)   NULL,
    [CultureCode]          NVARCHAR (10)    NULL,
    [CreatedByUserId]      UNIQUEIDENTIFIER NULL,
    [CreatedOnDate]        DATETIME         NULL,
    [LastModifiedByUserId] UNIQUEIDENTIFIER NULL,
    [LastModifiedOnDate]   DATETIME         NULL,
    PRIMARY KEY CLUSTERED ([ContainerId] ASC)
);

