CREATE TABLE [dbo].[Menu] (
    [ApplicationId]        UNIQUEIDENTIFIER NULL,
    [PositionId]           INT              NULL,
    [PageId]               INT              NULL,
    [TypeId]               INT              NULL,
    [MenuId]               INT              NOT NULL,
    [MenuCode]             UNIQUEIDENTIFIER NULL,
    [MenuName]             NVARCHAR (255)   NOT NULL,
    [MenuTitle]            NVARCHAR (255)   NULL,
    [MenuAlias]            NVARCHAR (255)   NOT NULL,
    [ParentId]             INT              NULL,
    [Depth]                INT              NOT NULL,
    [Lineage]              VARCHAR (250)    NULL,
    [ListOrder]            INT              NOT NULL,
    [HasChild]             BIT              CONSTRAINT [DF__Menu2__HasChild__524F1B17] DEFAULT ((0)) NULL,
    [Description]          NVARCHAR (4000)  NULL,
    [Target]               VARCHAR (10)     NULL,
    [IconClass]            NVARCHAR (50)    NULL,
    [IconFile]             INT              NULL,
    [Color]                NVARCHAR (50)    NULL,
    [CssClass]             NVARCHAR (50)    NULL,
    [IsSecured]            BIT              NULL,
    [Status]               INT              NOT NULL,
    [CreatedDate]          DATETIME         NULL,
    [CreatedByUserId]      UNIQUEIDENTIFIER NULL,
    [LastModifiedDate]     DATETIME         NULL,
    [LastModifiedByUserId] UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK__Menu2__C99ED230FC4A308C] PRIMARY KEY CLUSTERED ([MenuId] ASC)
);

