CREATE TABLE [dbo].[Menu3] (
    [ApplicationId]        UNIQUEIDENTIFIER NULL,
    [PageId]               INT              NULL,
    [ScopeTypeId]          INT              NOT NULL,
    [PositionId]           INT              NULL,
    [MenuId]               INT              NOT NULL,
    [MenuCode]             UNIQUEIDENTIFIER NULL,
    [ParentId]             INT              NULL,
    [Depth]                INT              NOT NULL,
    [Lineage]              VARCHAR (250)    NULL,
    [ListOrder]            INT              NOT NULL,
    [HasChild]             BIT              DEFAULT ((0)) NULL,
    [MenuName]             NVARCHAR (255)   NOT NULL,
    [MenuTitle]            NVARCHAR (255)   NULL,
    [MenuAlias]            NVARCHAR (255)   NOT NULL,
    [Description]          NVARCHAR (4000)  NULL,
    [Target]               CHAR (10)        NULL,
    [IconClass]            NVARCHAR (50)    NULL,
    [IconFile]             INT              NULL,
    [Color]                NVARCHAR (50)    NULL,
    [CssClass]             NVARCHAR (50)    NULL,
    [IsSecured]            BIT              NULL,
    [Status]               INT              NOT NULL,
    [CreatedDate]          DATETIME         NULL,
    [LastModifiedDate]     DATETIME         NULL,
    [CreatedByUserId]      INT              NULL,
    [LastModifiedByUserId] INT              NULL,
    PRIMARY KEY CLUSTERED ([MenuId] ASC)
);

