CREATE TABLE [dbo].[News] (
    [NewsId]               INT              IDENTITY (1, 1) NOT NULL,
    [CategoryId]           INT              NOT NULL,
    [VendorId]             INT              NULL,
    [Title]                NVARCHAR (400)   NOT NULL,
    [Headline]             NVARCHAR (400)   NOT NULL,
    [Alias]                NVARCHAR (400)   NULL,
    [Summary]              NVARCHAR (500)   NULL,
    [FrontImage]           INT              NULL,
    [MainImage]            INT              NULL,
    [MainText]             NVARCHAR (MAX)   NOT NULL,
    [NavigateUrl]          NVARCHAR (500)   NULL,
    [Authors]              NVARCHAR (50)    NULL,
    [ListOrder]            INT              NULL,
    [Tags]                 NVARCHAR (400)   NULL,
    [Source]               NVARCHAR (100)   NULL,
    [TotalRates]           INT              NULL,
    [TotalViews]           INT              NULL,
    [IsPublishedToFeed]    BIT              NULL,
    [IsCommentShowed]      BIT              NULL,
    [IsRatingShowed]       BIT              NULL,
    [Status]               INT              NOT NULL,
    [PostedDate]           DATETIME         NULL,
    [IP]                   VARCHAR (30)     NULL,
    [LastUpdatedIP]        VARCHAR (30)     NULL,
    [CreatedDate]          DATETIME         NULL,
    [LastModifiedDate]     DATETIME         NULL,
    [CreatedByUserId]      UNIQUEIDENTIFIER NULL,
    [LastModifiedByUserId] UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_News] PRIMARY KEY CLUSTERED ([NewsId] ASC)
);

