CREATE TABLE [dbo].[Page] (
    [ApplicationId]        UNIQUEIDENTIFIER NULL,
    [LanguageCode]         VARCHAR (50)     NOT NULL,
    [TemplateId]           INT              NULL,
    [ContentItemId]        INT              NULL,
    [PageId]               INT              IDENTITY (0, 1) NOT NULL,
    [PageTypeId]           INT              NULL,
    [PageCode]             VARCHAR (50)     CONSTRAINT [DF_Pages_PageCode] DEFAULT (newid()) NULL,
    [PageName]             NVARCHAR (200)   NOT NULL,
    [PageTitle]            NVARCHAR (200)   NOT NULL,
    [PageAlias]            NVARCHAR (200)   NULL,
    [PagePath]             NVARCHAR (255)   NOT NULL,
    [PageUrl]              NVARCHAR (255)   NULL,
    [ListOrder]            INT              NOT NULL,
    [IconFile]             INT              NULL,
    [IconClass]            VARCHAR (50)     NULL,
    [IconUrl]              NVARCHAR (MAX)   NULL,
    [Description]          NVARCHAR (500)   NULL,
    [Keywords]             NVARCHAR (500)   NULL,
    [PageHeadText]         NVARCHAR (500)   NULL,
    [PageFooterText]       NVARCHAR (MAX)   NULL,
    [DisableLink]          BIT              CONSTRAINT [DF_Pages_DisableLink] DEFAULT ((0)) NULL,
    [DisplayTitle]         BIT              CONSTRAINT [DF_Pages_DisplayTitle] DEFAULT ((1)) NOT NULL,
    [IsExtenalLink]        BIT              CONSTRAINT [DF_Pages_IsExtenalLink] DEFAULT ((0)) NULL,
    [IsMenu]               BIT              CONSTRAINT [DF_Pages_IsMenu] DEFAULT ((0)) NULL,
    [IsSecured]            BIT              CONSTRAINT [DF_Pages_IsSecured] DEFAULT ((0)) NOT NULL,
    [IsActive]             BIT              CONSTRAINT [DF_Pages_IsVisible] DEFAULT ((1)) NOT NULL,
    [StartDate]            DATETIME         NULL,
    [EndDate]              DATETIME         NULL,
    [Ip]                   VARCHAR (30)     NULL,
    [LastUpdatedIp]        VARCHAR (30)     NULL,
    [CreatedDate]          DATETIME         CONSTRAINT [DF_Pages_CreatedOnDate] DEFAULT (getdate()) NULL,
    [LastModifiedDate]     DATETIME         CONSTRAINT [DF_Pages_LastModifiedOnDate] DEFAULT (getdate()) NULL,
    [CreatedByUserId]      INT              NULL,
    [LastModifiedByUserId] INT              NULL,
    CONSTRAINT [PK__Pages__C565B10453649590] PRIMARY KEY CLUSTERED ([PageId] ASC)
);

