CREATE TABLE [dbo].[User] (
    [ApplicationId]                    UNIQUEIDENTIFIER NOT NULL,
    [UserId]                           UNIQUEIDENTIFIER CONSTRAINT [DF_Users_UserCode] DEFAULT (newid()) NOT NULL,
    [SeqNo]                            INT              NOT NULL,
    [UserName]                         NVARCHAR (256)   NOT NULL,
    [LoweredUserName]                  NVARCHAR (256)   NOT NULL,
    [Password]                         NVARCHAR (128)   NOT NULL,
    [PasswordSalt]                     NVARCHAR (128)   NOT NULL,
    [PasswordQuestion]                 NVARCHAR (256)   NULL,
    [PasswordAnswer]                   NVARCHAR (128)   NULL,
    [UpdatePassword]                   BIT              CONSTRAINT [DF_Users_UpdatePassword] DEFAULT ((1)) NULL,
    [EmailConfirmed]                   BIT              NULL,
    [LastPasswordChangedDate]          DATETIME         NULL,
    [FailedPasswordAttemptCount]       INT              NULL,
    [FailedPasswordAttemptTime]        DATETIME         NULL,
    [FailedPasswordAnswerAttemptCount] INT              NULL,
    [FailedPasswordAnswerAttemptTime]  DATETIME         NULL,
    [StartDate]                        DATETIME         NULL,
    [ExpiredDate]                      DATETIME         NULL,
    [IsApproved]                       BIT              CONSTRAINT [DF_Users_IsApproved] DEFAULT ((1)) NULL,
    [IsLockedOut]                      BIT              CONSTRAINT [DF_Users_IsLockedOut] DEFAULT ((0)) NULL,
    [IsSuperUser]                      BIT              CONSTRAINT [DF_Users_IsSuperUser] DEFAULT ((0)) NULL,
    [LastLoginDate]                    DATETIME         NULL,
    [LastLockoutDate]                  DATETIME         NULL,
    [Ip]                               NVARCHAR (50)    NULL,
    [LastUpdatedIp]                    NVARCHAR (50)    NULL,
    [CreatedDate]                      DATETIME         CONSTRAINT [DF_Users_CreatedOnDate] DEFAULT (getdate()) NULL,
    [LastModifiedDate]                 DATETIME         NULL,
    [CreatedByUserId]                  INT              NULL,
    [LastModifiedByUserId]             INT              NULL,
    [LastActivityDate]                 DATETIME         NULL,
    CONSTRAINT [PK__Users__1788CC4D99AE891E] PRIMARY KEY NONCLUSTERED ([UserId] ASC)
);

